#######################################################################################
##  Configuration file with control group definitions for resource allocation         #
#######################################################################################
## - The actual CPU allocation is hardware specific. It depends on the
##   hardware make and model and the type of CPU(s) in the system.
##   controlGroupSchemes.controlgroups.dimensions.allowedCpus and
##   controlGroupSchemes.controlgroups.dimensions.allowedMemoryNodes
##   must be determined to create a valid configuration.
##   The System Dimensioning Guide and CSS User Guide contains additional information.
##   Note: The CPU allocation rules are defined in CPU cores, but the
##   parameters below use CPU IDs. When simultaneous multithreading (SMT)
##   is enabled, a CPU core maps to 2 CPU IDs (threads).
## - Multi-level control group definitions are not supported.
---
controlGroupSchemes:
  # control hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 1+1 setup
  - name: HPE_control_Xeon6330N
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,28,84'
    - name: css
      dimensions:
        allowedCpus: '0-1,57,29,85'
    - name: container
      dimensions:
        allowedCpus: '2-7,58-63,30-35,86-91'
        allowedMemoryNodes: '0,1'
    - name: machine
      dimensions:
        allowedCpus: '8-27,64-83,36-55,92-111'
        allowedMemoryNodes: '0,1'
  # compute hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 1+1 setup
  - name: HPE_compute_Xeon6330N
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,28,84'
    - name: css
      dimensions:
        allowedCpus: '0-1,57,29,85'
    - name: machine
      dimensions:
        allowedCpus: '2-27,58-83,30-55,86-111'
        allowedMemoryNodes: '0,1'
    - name: container
      dimensions:
        allowedCpus: '0,56,28,84'
        allowedMemoryNodes: '0,1'
  # control hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 1+1 setup
  - name: DELL_control_Xeon6330N
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,1,57'
    - name: css
      dimensions:
        allowedCpus: '0-3,56-59'
    - name: container
      dimensions:
        allowedCpus: '5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111'
        allowedMemoryNodes: '1'
    - name: machine
      dimensions:
        allowedCpus: '4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110'
        allowedMemoryNodes: '0'
  # compute hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 1+1 setup
  - name: DELL_compute_Xeon6330N
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,1,57'
    - name: css
      dimensions:
        allowedCpus: '0,2,58,3,59'
    - name: machine
      dimensions:
        allowedCpus: '4-55,60-111'
        allowedMemoryNodes: '0,1'
    - name: container
      dimensions:
        allowedCpus: '0,56,1,57'
        allowedMemoryNodes: '0,1'
        
  # compute hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 1+1 setup
  - name: DELL_compute_Xeon6330N_compute_vxsds_hc
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,4,6,56,60,62,1,5,7,57,61,63'
    - name: css
      dimensions:
        allowedCpus: '0,2,4,6,1,3,5,7,56,58,60,62,57,59,61,63'
    - name: machine
      dimensions:
        allowedCpus: '8-55,64-111'
        allowedMemoryNodes: '0,1'
    - name: container
      dimensions:
        allowedCpus: '0,4,6,56,60,62,1,5,7,57,61,63'
        allowedMemoryNodes: '0,1'
        

  - name: virtualhost_controlgroup
    controlGroups:
    - name: system
    - name: container
  - name: infra_controlgroup
    controlGroups:
    - name: container
  # control hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 2+2 setup
  - name: DELL_control_Xeon6330N_2_plus_2
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,1,57'
    - name: css
      dimensions:
        allowedCpus: '0,2-5,58-61'
    - name: container
      dimensions:
        allowedCpus: '6-15,62-71'
        allowedMemoryNodes: '0,1'
    - name: machine
      dimensions:
        allowedCpus: '16-55,72-111'
        allowedMemoryNodes: '0,1'
  # compute hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 2+2 setup
  - name: DELL_compute_Xeon6330N_2_plus_2
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,1,57'
    - name: css
      dimensions:
        allowedCpus: '0,2-5,58-61'
    - name: machine
      dimensions:
        allowedCpus: '6-55,62-111'
        allowedMemoryNodes: '0,1'
    - name: container
      dimensions:
        allowedCpus: '0,57'
        allowedMemoryNodes: '0,1'
  # control hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 2+2 setup
  - name: HPE_control_Xeon6330N_2_plus_2
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,28,84'
    - name: css
      dimensions:
        allowedCpus: '0-2,57-58,29-30,85-86'
    - name: container
      dimensions:
        allowedCpus: '3-7,59-63,31-35,87-91'
        allowedMemoryNodes: '0,1'
    - name: machine
      dimensions:
        allowedCpus: '8-27,64-83,36-55,92-111'
        allowedMemoryNodes: '0,1'
  # compute hosts 1 Intel Xeon Gold 6330N 112vCPU
  # High ovs performance 2+2 setup
  - name: HPE_compute_Xeon6330N_2_plus_2
    controlGroups:
    - name: system
      dimensions:
        allowedCpus: '0,56,28,84'
    - name: css
      dimensions:
        allowedCpus: '0-2,57-58,29-30,85-86'
    - name: machine
      dimensions:
        allowedCpus: '3-27,59-83,31-55,87-111'
        allowedMemoryNodes: '0,1'
    - name: container
      dimensions:
        allowedCpus: '0,84'
        allowedMemoryNodes: '0,1'
...
...
