---
memoryAssignments:
  - name: compute_memory_512GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 200
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 200
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 400
  - name: control_memory_512GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 200
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 200
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_qemu_1G
        owner: libvirt
        count: 400
  - name: compute_memory_768GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 300
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 300
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 600
  - name: compute_memory_384GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 150
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 150
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 300
  - name: compute_memory_192GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 80
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 80
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 160
  - name: control_memory_384GB
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 80
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 80
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_qemu_1G
        owner: libvirt
        count: 160
...
