---

portProfiles:
  - name: HPE_DL380_G10_nic_assignment_mlx
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:48:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:48:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:0f:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:0f:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:2b:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:2b:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_control
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:31:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:31:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_control2
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:4b:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:4b:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_control3
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:4b:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:4b:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_compute-2-7
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:4b:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:4b:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt0
        busAddress: "0000:b1:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt1
        busAddress: "0000:b1:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt2
        busAddress: "0000:31:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt3
        busAddress: "0000:31:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_compute-2-8
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:98:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:98:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:31:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:31:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt0
        busAddress: "0000:4b:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt1
        busAddress: "0000:4b:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt2
        busAddress: "0000:b1:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt3
        busAddress: "0000:b1:00.1"
        lldp:
          adminStatus: tx-only
  - name: DELL_R650_nic_assignment_compute_highBW
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:31:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:31:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt0
        busAddress: "0000:4b:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt1
        busAddress: "0000:4b:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt2
        busAddress: "0000:b1:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt3
        busAddress: "0000:b1:00.1"
        lldp:
          adminStatus: tx-only          
  - name: DELL_R650_nic_assignment_compute_std
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:04:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:04:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:31:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:31:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:98:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:98:00.1"
        lldp:
          adminStatus: tx-only
#      - name: pt0
#        busAddress: "0000:4b:00.0"
#        lldp:
#          adminStatus: tx-only
#      - name: pt1
#        busAddress: "0000:4b:00.1"
#        lldp:
#          adminStatus: tx-only
#      - name: pt2
#        busAddress: "0000:b1:00.0"
#        lldp:
#          adminStatus: tx-only
#      - name: pt3
#        busAddress: "0000:b1:00.1"
#        lldp:
#          adminStatus: tx-only          
  - name: HPE_DL380_G10_nic_assigment_compute-2-4_5
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:48:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:48:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:2b:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:2b:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:0f:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:0f:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt0
        busAddress: "0000:a2:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt1
        busAddress: "0000:a2:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt2
        busAddress: "0000:84:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt3
        busAddress: "0000:84:00.1"
        lldp:
          adminStatus: tx-only
  - name: HPE_DL380_G10_nic_assigment_compute-2-6
    ports:
      - name: control0
        aggregator: control
        busAddress: "0000:48:00.0"
        lldp:
          adminStatus: tx-only
      - name: control1
        aggregator: control
        busAddress: "0000:48:00.1"
        lldp:
          adminStatus: tx-only
      - name: data0
        aggregator: traffic
        busAddress: "0000:0f:00.0"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: data1
        aggregator: traffic
        busAddress: "0000:0f:00.1"
        driver: mlx5_core
        lldp:
          adminStatus: tx-only
      - name: storage0
        aggregator: storage
        busAddress: "0000:84:00.0"
        lldp:
          adminStatus: tx-only
      - name: storage1
        aggregator: storage
        busAddress: "0000:84:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt0
        busAddress: "0000:2b:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt1
        busAddress: "0000:2b:00.1"
        lldp:
          adminStatus: tx-only
      - name: pt2
        busAddress: "0000:a2:00.0"
        lldp:
          adminStatus: tx-only
      - name: pt3
        busAddress: "0000:a2:00.1"
        lldp:
          adminStatus: tx-only

  - name: VIRTUAL_INFRA
    virtualPorts:
      - name: lcm
        aggregator: control
        busAddress: "0000:01:00.0"
        networkInterface: br_lcm_ctrl
      - name: control
        aggregator: control
        busAddress: "0000:02:00.0"
        networkInterface: br_cee_ctrl
      - name: data
        aggregator: traffic
        busAddress: "0000:03:00.0"
        networkInterface: br_lcm_om
      - name: gluster
        aggregator: storage
        busAddress: "0000:04:00.0"
        networkInterface: br_gluster
  - name: VIRTUAL_CSC
    virtualPorts:
      - name: lcm
        aggregator: control
        busAddress: "0000:01:00.0"
        networkInterface: br_lcm_ctrl
      - name: control
        aggregator: control
        busAddress: "0000:02:00.0"
        networkInterface: br_cee_ctrl
      - name: sdn_sbi
        aggregator: traffic
        busAddress: "0000:03:00.0"
        networkInterface: br_sdnc_sbi
      - name: sdn_int
        aggregator: traffic
        busAddress: "0000:04:00.0"
        networkInterface: br_sdnc_internal
...
