#######################################################################################
##  Configuration file with CEE service component frontends information               #
#######################################################################################
---
serviceComponentFrontends:
  - name: cee_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: openstack_internal_tls
    virtualIP: openstack_int_vip
    region: CEERegion   #changed cee10.4 Openstackregion
    endpointTypes:
      - internal
      - admin
  - name: cee_external_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: openstack_external_tls
    virtualIP: openstack_ext_vip
    region: CEERegion    #OpenStackRegion
    endpointTypes:
      - public
  - name: glance_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: glance_internal_tls
    virtualIP: glance_int_vip
    region: CEERegion  #OpenStackRegion
    endpointTypes:
      - internal
      - admin
  - name: infra_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: infra_internal_tls
    virtualIP: lcm_int_vip
    region: InfraRegion
    endpointTypes:
      - internal
      - admin
  - name: infra_external_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: infra_external_tls
    virtualIP: lcm_ext_vip
    region: InfraRegion
    endpointTypes:
      - public
  - name: lcm_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: lcm_internal_tls
    virtualIP: lcm_int_vip
    region: LCMRegion
    endpointTypes:
      - internal
      - admin
  - name: lcm_external_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: lcm_external_tls
    virtualIP: lcm_ext_vip
    region: LCMRegion
    endpointTypes:
      - public
  - name: serviceassurance_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: serviceassurance_internal_tls
    virtualIP: serviceassurance_int_vip
    region: InfraRegion
    endpointTypes:
      - internal
      - admin
  - name: serviceassurance_external_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: serviceassurance_external_tls
    virtualIP: serviceassurance_ext_vip
    region: InfraRegion
    endpointTypes:
      - public
  - name: sdnc_nbi_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: sdnc_nbi_tls
    virtualIP: sdnc_nbi_vip
    endpointTypes:
    ## TODO: this should be internal, but maintained as 'public' to
    ## match the current generators.
      - public
  - name: sdnc_sbi_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: sdnc_sbi_tls
    virtualIP: sdnc_sbi_vip
    endpointTypes:
      - internal
  - name: vxsds_internal_frontend
    provider: haproxy
    protocol: https
    transportLayerSecurity: vxsds_internal_tls
    virtualIP: vxsds_int_vip
    endpointTypes:
      - internal
...
