#######################################################################################
##  Configuration file with CEE software allocation                                   #
#######################################################################################
---
softwareAllocations:
  - name: hostOS_sp3
    software:
      - name: hostos_sp3
        version: sles15sp3
      - name: cee_host_extras_sp3
        version: sles15sp3
  - name: container_v1
    software:
      - name: container
        version: 10.5.0.15.0.6
  - name: lcm_v1
    software:
      - name: cee_infra
        version: 1.0
  - name: portal_v1
    software:
      - name: portal
        version: 1.0
      - name: cee_alarm_opi
        version: 1.0
  - name: alarmopi_v1
    software:
      - name: cee_alarm_opi
        version: 1.0
  - name: openstack_v1
    software:
      - name: openstack
        version: 1.0
  - name: serviceassurance_v1
    software:
      - name: cee_serviceassurance
        version: 1.0
  - name: CSS_v1
    software:
      - name: css
        version: 1.0
  - name: vxsds_sp3
    software:
      - name: vxsds_sp3
        version: 3.6.0.6-sp3
  - name: vxsds_client_sp3
    software:
      - name: vxsds_client_sp3
        version: 3.6.0.6-sp3
  - name: csc_v1
    software:
      - name: csc
        version: 1.0
  - name: csc_drivers_v1
    software:
      - name: csc_drivers
        version: 1.0
  - name: sdi_v1
    software:
      - name: sdi-agent
        version: 1.0

...
