---
software:
  - name: hostos_sp3
    versions:
      - version: sles15sp3
        url: '/repos/CXC1742929_8-R6A15-dbb42d094e-6/ericsson-host-os'
    type: rpm-md
    priority: 99
    release: 'SLES 15 SP3'
  - name: cee_host_extras_sp3
    versions:
      - version: sles15sp3
        url: '/repos/CXC1742929_8-R6A15-dbb42d094e-6/ericsson-host-extras'
    type: rpm-md
    release: 'SLES 15 SP3'
  - name: openstack
    versions:
      - version: 1.0
        url: '/repos/CXC1742930_8-R6A15-dbb42d094e-6/ericsson-openstack'
    type: rpm-md
    release: 'OpenStack Victoria'
  - name: container
    versions:
      - version: 10.5.0.15.0.6
        url: ':5500/cee/'
    type: docker
    release: 'CEE 10.4'
  - name: cee_infra 
    versions:
      - version: 1.0
        url: '/repos/CXC1737883_8-R6A15-dbb42d094e-6/cee-infra'
    type: rpm-md
    release: 'CEE 10.4'
  - name: cee_serviceassurance
    versions:
      - version: 1.0
        url: '/repos/CXC1742932_8-R6A15-dbb42d094e-6/ericsson-serviceassurance'
    type: rpm-md
    release: 'CEE 10.4'
  - name: portal
    versions:
      - version: 1.0
        url: '/repos/CXC1742933_8-R6A15-dbb42d094e-6/ericsson-portal-orchestrator'
    type: rpm-md
    release: 'CEE 10.4'
  - name: cee_alarm_opi
    versions:
      - version: 1.0
        url: '/repos/CXC1743854_8-R6A15-dbb42d094e-6/ericsson-cee-alarm-opi/cee-alarm-opi'
#        url: '/repos/CXC1743854_8-R6A15-af3c968c9c-7/ericsson-cee-alarm-opi/cee-alarm-opi'
    type: rpm-md
    release: 'CEE 10.4'
#  - name: ctt
#    versions:
#      - version: 1.0
#        url: '/repos/CXC1742654_8-<TO.BE.FILLED>/ericsson-ctt-orchestrator'
#    type: rpm-md
#    release: 'CEE 10.4'
  - name: css
    versions:
      - version: 1.0
        url: '/repos/CXP9042331_7-R1N-e6d5de6/ericsson-css'
    type: rpm-md
    priority: 80
    release: 'CSS7'
  - name: vxsds_sp3
    versions:
      - version: 3.6.0.6-sp3
        url: '/repos/CXC1740177_8-R6A15-dbb42d094e-6/ericsson-vxsds-server'
    type: rpm-md
    priority: 80
    release: 'PowerFlex 3.6.0.6'
  - name: vxsds_client_sp3
    versions:
      - version: 3.6.0.6-sp3
        url: '/repos/CXC1743286_8-R6A15-dbb42d094e-6/ericsson-vxsds-client'
    type: rpm-md
    priority: 80
    release: 'PowerFlex 3.6.0.6'
  - name: csc_drivers
    versions:
      - version: 1.0
        url: '/repos/CXP9041489_8-R4A30-f35cea4/ericsson-csc-drivers'
    type: rpm-md
    release: 'OpenDayLight Oxygen'
  - name: csc
    versions:
      - version: 1.0
        url: '/repos/CXP9041489_8-R4A30-f35cea4/ericsson-csc'
    type: rpm-md
    release: 'OpenDayLight Oxygen'
  - name: sdi-agent
    versions:
      - version: 1.0
        url: '/repos/CXC1740740_8-R6A15-dbb42d094e-6/ericsson-sdi-agent-orchestrator'
    type: rpm-md
    release: 'SDI 2.19'
...

