vnflcm:
  vnfInstanceName: n186-eccd1-cces1
  vnfProductName: CCES
  vnfSoftwareVersion: 1.11.3+45
  instantiate-file: instantiate.json
  values-file: values.yaml
  clusterName: n186-eccd1
  namespace: cces1
access-info:
  oam: cces1-oam.n186-eccd1.seli.gic.ericsson.se
  ldap-admin:
    user: sysadmin
    pass: c3lzQWRtMW5ARGF5MA==
  users:
  - user: cces-admin
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
  - user: cces-sec
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
pipeline:
- module: create-namespace
- module: create-k8s-secret
  name: eric-sec-ldap-server-creds
  sources:
  - type: literal
    key: adminuser
    value: sysadmin
  - type: literal
    key: passwd
    value: sysAdm1n@Day0
  - type: literal
    key: adminpasswd
    value: $6$fzLPYlRZCpweJMJC$AiNfP0WYE3npY8Za6GxMFoGj75TOl.TS6tmnnky2Bv5wY0Ek8RIoJlr9pyj0LF3wMMaNsNTUH4jp2lIHviJGS0
- module: create-k8s-secret
  name: snmp-alarm-provider-config
  sources:
  - type: file
    key: config.json
    file: snmp-config.json
- module: create-k8s-secret
  name: eric-data-distributed-coordinator-creds
  sources:
  - type: literal
    key: etcdpasswd
    value: sysAdm1n@Day0
- module: create-k8s-secret
  name: eric-sec-access-mgmt-creds
  sources:
  - type: literal
    key: kcadminid
    value: admin
  - type: literal
    key: kcpasswd
    value: sysAdm1n@Day0
- module: create-k8s-secret
  name: sftp-server-config
  sources:
  - type: file
    key: sftpConfig.json
    file: sftp-config.json
- module: instantiate
- module: verify-pod-running
  ignore-not-running:
  - eric-data-search-engine-curator
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: network-policy/eric-pm-server-allow.yaml
    file2: network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: Modify eric-cces-nf-monitor Service
  cmd: |-
    patch svc eric-cces-nf-monitor -p '{"metadata":{"annotations":{"prometheus.io/scrape":"true"}}}' --type=merge
    patch svc eric-cces-nf-monitor -p '{"metadata":{"annotations":{"prometheus.io/path":"/metrics"}}}' --type=merge
    patch svc eric-cces-nf-monitor -p '{"metadata":{"annotations":{"prometheus.io/port":"8082"}}}' --type=merge
- module: run-k8s-command
  name: Create pm server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-cces.ingress.n186-eccd1.seli.gic.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: load-cmyp-user-config
  file: user-config.xml
  proto: netconf
  retry-interval: 30
- module: sleep
  duration: 30
- module: change-initial-password
- module: load-cmyp-app-config
  file: external-certificates.xml
  user-id: 1
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: nef-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: nef-diameter-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: nrfagent-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ddc-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 60
- module: provision-nef
  host: cces1-5g-prov.n186-eccd1.seli.gic.ericsson.se
  trustca: ../../../certs/RootCA/ca.crt
  client-cert: ../../../certs/n186-eccd1/cces1/cces1-prov-client.crt
  client-key: ../../../certs/n186-eccd1/cces1/cces1-prov-client.key
  prov-info:
  - api-path: Provisioning/generic/entity/v2
    data-file: nef-provisioning/1_ServiceProvider.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: nef-provisioning/2_ServiceProviderServiceSubscription.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: nef-provisioning/3_Application.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: nef-provisioning/4_ApplicationServiceSubscription.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/qos/v1/information/QI_001
    data-file: nef-provisioning/5_QoS_information.json
    method: PUT
    headers:
      Content-Type: application/json
  - api-path: Provisioning/qos/v1/information/QI_002
    data-file: nef-provisioning/6_QoS_information.json
    method: PUT
    headers:
      Content-Type: application/json
