nodeName: n186-eccd1-eda1
nodeType: EDA

vnflcm:
  clusterName: n186-eccd1
  namespace: eda1
#  InstantiateVnfRequest:
#    applicationTimeOut: 1800
#    skipVerification: "false"

license:
  customerId: '946060'
  swltId: STA-EDA-1

eda:
  domainName: seli.gic.ericsson.se
  clusterName: eda1-oam.n186-eccd1
  hssValidatorTag: 1.29.102

snmp:
  agentEngineId: 800000c104454441a1c1d1

pvcSize:
  eric-data-wide-column-database-cd: 114
  eric-data-message-bus-kf: 2
replicaCount:
  eric-act-aaa: 1
  eric-tm-ingress-controller-cr-envoy: 4
  eric-act-inbound-async: 1
  eric-act-inbound-interfaces: 1
  eric-act-inbound-mml: 1
  eric-act-rest-provisioning: 1
  eric-act-web-server: 1
instance: 1
