{
 "title": "Cluster-CPU-Mem-Utilization-Container",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_last_seen{}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{namespace=~\"$namespace\",pod=~\".*$pod.*\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU Usage by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}[5m]) / on(namespace,pod,container)group_left() (kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"cpu\"})",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"} - container_memory_cache{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}) / on(namespace,pod,container)group_left() kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"memory\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage by limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}[5m]) / on(namespace,pod,container)group_left() (kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"cpu\"})",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage by limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"} - container_memory_cache{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}) / on(namespace,pod,container)group_left() kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"memory\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Request",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Request",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=~\"memory\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Limit",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Limit",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\",resource=~\"memory\"}",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Absolute Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}[5m])",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container Memory Absolute Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"} - container_memory_cache{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"})",
     "legendFormat": "{{namespace}}_{{pod}}_{{container}}"
    },
    {
     "expr": "sum((container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"} - container_memory_cache{namespace=~\"$namespace\",pod=~\".*$pod.*\",container=~\"$container\"}))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}