{
 "title": "Cluster-CPU-Mem-Utilization-Namespace",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_last_seen{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace CPU Usage by request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}[5m])) by (namespace) / on(namespace)group_left() sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"cpu\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage by request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace)) - (sum(container_memory_cache{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace))) / on(namespace)group_left() sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Usage by limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}[1m])) by (namespace) / on(namespace)group_left() sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"cpu\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage by limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace)) - (sum(container_memory_cache{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace))) / on(namespace)group_left() sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Absolute Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Namespace Memory Absolute Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace)) - (sum(container_memory_cache{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) by (namespace)))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"}) - sum(container_memory_cache{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",container!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Namespace CPU Request",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"cpu\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Request",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Limit",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"cpu\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Limit",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod!~\"eric-pc-up-data-plane.*\",resource=\"memory\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } }
 ]
}