{
 "title": "Cluster-Disk-IO-Statistics-Host",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_disk_reads_completed_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reads per Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(sum(irate(node_disk_reads_completed_total{instance=~'$node'}[5m]))by(instance)) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "sum(irate(node_disk_reads_completed_total{instance=~'$node'}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Writes per Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(sum(irate(node_disk_writes_completed_total{instance=~'$node'}[5m]))by(instance)) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{instance=~'$node'}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Read IOPS per device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(irate(node_disk_reads_completed_total{instance=~'$node',device=~\"$device\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  },
  {
   "title": "Write IOPS per device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(irate(node_disk_writes_completed_total{instance=~'$node',device=~\"$device\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  },
  {
   "title": "Read latency per device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  },
  {
   "title": "Write latency per device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  }
 ]
}