{
 "title": "Cluster_Overview",
 "description": "Summary metrics about containers running on Kubernetes nodes and mainline kubernetes statistics",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "ds", "query": { "query": "datasource" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Unavailable",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 7, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node!~\"master.*\"})by(node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node!~\"master.*\"})by(node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node!~\"master.*\"})by(node)-sum(kube_pod_container_resource_requests_cpu_cores{node!~\"master.*\"})by(node)"
    }
   ]
  },
  {
   "title": "Cluster MEM Capacity",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 8, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"master.*\"})by(node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node!~\"master.*\"})by(node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"master.*\"})by(node)-sum(kube_pod_container_resource_requests_memory_bytes{node!~\"master.*\"})by(node)"
    }
   ]
  },
  {
   "title": "Volumes Full Prediction",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(\n  (\n    (\n      (kubelet_volume_stats_used_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\"})\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Pods_Container Running",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"kube-system|ccsm|ccrc|ccdm|pcc|monitoring|eda2|eric-crd-ns|ingress-nginx|default\", phase=\"Running\"})",
     "legendFormat": "POD_Number"
    },
    {
     "expr": "0-sum(kube_pod_container_status_running{namespace=~\"kube-system|ccsm|ccrc|ccdm|pcc|monitoring|eda2|eric-crd-ns|ingress-nginx|default\"})",
     "legendFormat": "Container_Number"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pod-Level-PacketDrop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{name=~\".+\",namespace=~\"default\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    },
    {
     "expr": "-sum(irate(container_network_send_packets_dropped_total{name=~\".+\",namespace=~\"default\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace!=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Actived",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "POD_Restart",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) by(namespace,pod) -sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"} offset 5m) by(namespace,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}