{
 "title": "Cluster-CPU-Mem-Utilization-Host",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=~\"$node\"},cpu)"
    }
   },
   {
    "name": "mode",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=~\"$node\"},mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host CPU overall",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance)) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum((node_memory_MemTotal_bytes{instance=~'$node'}-(node_memory_MemFree_bytes{instance=~'$node'}+node_memory_Cached_bytes{instance=~'$node'}+node_memory_Buffers_bytes{instance=~'$node'}))/node_memory_MemTotal_bytes{instance=~'$node'}) by (instance)) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Host CPU overall per mode",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=~\"$mode\"}[5m])) by (instance, mode)) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{mode}}"
    }
   ]
  },
  {
   "title": "Host CPU per CPU per mode",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{instance=~\"$node\", cpu=~\"$CPU\", mode=~\"$mode\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_CPU_{{cpu}}_{{mode}}"
    }
   ]
  }
 ]
}