{
 "title": "CNF-Overload-Statistics-CCSM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "max:eric_udm_nudm_overload_unsuccessful_ratio:rate1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max:eric_udm_nudm_ueau_overload_unsuccessful_ratio:rate1m",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "max:eric_udm_nudm_uecm_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "max:eric_udm_nudm_sdm_overload_unsuccessful_ratio:rate1m"
    }
   ]
  },
  {
   "title": "max:eric_ccsm_aspect_overload_unsuccessful_ratio:rate1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max:eric_ccsm_aspect_authentication_overload_unsuccessful_ratio:rate1m",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "max:eric_ccsm_aspect_ueregistration_overload_unsuccessful_ratio:rate1m"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max:eric_ccsm_aspect_pdusessionmngmt_overload_unsuccessful_ratio:rate1m",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "max:eric_ccsm_aspect_nudrnotifications_overload_unsuccessful_ratio:rate1m"
    }
   ]
  },
  {
   "title": "sum:eric_udm_nudm_overload_unsuccessful_ratio:rate1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum:eric_udm_nudm_sdm_amdata_overload_unsuccessful_ratio:rate1m",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_multipledataset_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_notify_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_nssai_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_smdata_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_smfselectdata_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_subscriptions_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_sdm_uectxtsmfdata_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_ueau_generateauth_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_amfdereg_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_amfget_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_amfreg_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_amfregupdate_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_smfdereg_overload_unsuccessful_ratio:rate1m"
    },
    {
     "expr": "sum:eric_udm_nudm_uecm_smfreg_overload_unsuccessful_ratio:rate1m"
    }
   ]
  }
 ]
}