{
 "title": "CNF-Traffic-Statistics-CCES",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "NRF Agent Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nrfagent_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_requests_sent[1m]))by(job,patch,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    }
   ]
  },
  { "title": "NEF Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "eric_apigm_apiproxy_north_requests_recv_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(eric_apigm_apiproxy_north_requests_recv_total[1m]))by(api,app,code,job,sp,sub)"
    }
   ]
  },
  {
   "title": "eric_apigm_apiproxy_north_success_transaction_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(eric_apigm_apiproxy_north_success_transaction_seconds_count[1m]))by(api,app,code,job,sp,sub)"
    }
   ]
  },
  {
   "title": "eric_apigm_apiproxy_north_failure_transaction_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(eric_apigm_apiproxy_north_failure_transaction_seconds_count[1m]))by(api,app,code,job,sp,sub)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_provisioning_requests_recv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_provisioning_requests_recv[1m]))by(job,operation,resource)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_provisioning_successful_responses_sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_provisioning_successful_responses_sent[1m]))by(job,operation,resource)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_provisioning_unsuccessful_responses_sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_provisioning_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,resource,status_code,detailed_info)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_requests_recv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_requests_recv[1m]))by(job,operation,resource)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_successful_responses_sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_successful_responses_sent[1m]))by(job,operation,resource)"
    }
   ]
  },
  {
   "title": "eric_nef_nnef_afsessionwithqos_unsuccessful_responses_sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nnef_afsessionwithqos_unsuccessful_responses_sent[1m]))by(job,operation,resource,status_code)"
    }
   ]
  },
  {
   "title": "eric_nef_nbsf_management_requests_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nbsf_management_requests_sent[1m]))by(job,operation,service)"
    }
   ]
  },
  {
   "title": "eric_nef_nbsf_management_successful_responses_recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nbsf_management_successful_responses_recv[1m]))by(job,operation,service)"
    }
   ]
  },
  {
   "title": "eric_nef_nbsf_management_unsuccessful_responses_recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(eric_nef_nbsf_management_unsuccessful_responses_recv[1m]))by(job,operation,service,status_code)"
    }
   ]
  }
 ]
}