{
 "title": "CNF-Traffic-Statistics-CCSM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "NRF Agent Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_nrfagent_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_requests_sent[1m]))by(job,patch,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    }
   ]
  },
  {
   "title": "AUTH Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_ausf_nausf_auth_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nausf_auth_requests_recv[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_ausf_nausf_auth_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nausf_auth_successful_responses_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_ausf_nausf_auth_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nausf_auth_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_ausf_nudm_ueau_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nudm_ueau_successful_responses_recv[1m]))by(job,operation,remote_endpoint,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_ausf_nudm_ueau_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nudm_ueau_requests_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_ausf_nudm_ueau_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ausf_nudm_ueau_unsuccessful_responses_recv[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_ueau_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_ueau_requests_recv[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_ueau_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_ueau_successful_responses_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_ueau_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_ueau_unsuccessful_responses_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UDM Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_udm_nudm_sdm_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_sdm_requests_recv[1m]))by(job,operation,req_info,remote_endpoint,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_sdm_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_sdm_successful_responses_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_sdm_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_sdm_unsuccessful_responses_sent[1m]))by(job,operation,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_uecm_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_uecm_requests_recv[1m]))by(job,operation,req_info,remote_endpoint,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_uecm_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_uecm_successful_responses_sent[1m]))by(job,operation,remote_endpoint,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudm_uecm_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudm_uecm_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HSS-EPC Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_hss_s6a_air_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_air_requests_recv[1m]))by(job,is_resync,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_air_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_air_successful_responses_sent[1m]))by(job,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_air_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_air_unsuccessful_responses_sent[1m]))by(job,detailed_info,result_code)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_ulr_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_ulr_requests_recv[1m]))by(job,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_ulr_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_ulr_successful_responses_sent[1m]))by(job,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_ulr_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_ulr_unsuccessful_responses_sent[1m]))by(job,detailed_info,result_code)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_pur_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_pur_requests_recv[1m]))by(job,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_pur_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_pur_successful_responses_sent[1m]))by(job,remote_endpoint)"
      }
     ]
    },
    {
     "title": "eric_hss_s6a_pur_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hss_s6a_pur_unsuccessful_responses_sent[1m]))by(job,detailed_info,result_code)"
      }
     ]
    }
   ]
  },
  {
   "title": "EIR Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_5g_eir_n5g_eir_eic_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_n5g_eir_eic_requests_recv[1m]))by(job,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_5g_eir_n5g_eir_eic_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_n5g_eir_eic_successful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_5g_eir_n5g_eir_eic_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_n5g_eir_eic_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_5g_eir_n5g_eir_socshipper_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_eir_socshipper_requests_recv[1m]))by(job,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_5g_eir_n5g_eir_socshipper_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_eir_socshipper_successful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_5g_eir_n5g_eir_socshipper_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_eir_socshipper_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_eir_diametereireic_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_diametereireic_requests_recv[1m]))by(job,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_eir_diametereireic_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_diametereireic_successful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    },
    {
     "title": "eric_eir_diametereireic_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_diametereireic_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)"
      }
     ]
    }
   ]
  },
  {
   "title": "UDR Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_udm_nudr_dr_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudr_dr_requests_sent[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudr_dr_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudr_dr_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_udm_nudr_dr_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udm_nudr_dr_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_5g_eir_ncudr_gud_dr_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_requests_sent[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_5g_eir_ncudr_gud_dr_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_5g_eir_ncudr_gud_dr_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_hssepc_ncudr_gud_dr_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hssepc_ncudr_gud_dr_requests_sent[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_hssepc_ncudr_gud_dr_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hssepc_ncudr_gud_dr_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_hssepc_ncudr_gud_dr_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_hssepc_ncudr_gud_dr_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code,detailed_info)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}} {{status_code}} {{detailed_info}}"
      }
     ]
    },
    {
     "title": "eric_eir_ncudr_gud_dr_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_requests_sent[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_eir_ncudr_gud_dr_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    },
    {
     "title": "eric_eir_ncudr_gud_dr_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_eir_ncudr_gud_dr_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource)",
       "legendFormat": "{{job}} {{operation}} {{remote_endpoint}} ({{req_info}}) {{resource}}"
      }
     ]
    }
   ]
  }
 ]
}