{
 "title": "Dm5gc-System-Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "stability_elapsed_time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stability_lead_time" }
   ]
  },
  {
   "title": "dallas_signaling_kpi",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(1-dallas_system_total_signaling_failed/(dallas_system_total_signaling_successful+dallas_system_total_signaling_resendings))",
     "legendFormat": "sig_KPI"
    }
   ]
  },
  {
   "title": "bsf_kpi",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100*sum(((bsf_out_answers_total{status=~\"2.*\"} @ end() ) - (bsf_out_answers_total @ start() ))) / (sum(bsf_in_requests_total{nf='bsf'} @ end()) - sum(bsf_in_requests_total{nf='bsf'} @ start())))"
    }
   ]
  },
  {
   "title": "dallas_throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(dallas_ltt_payload_gi_ul_bytes_rate+dallas_ltt_payload_gn_iuu_dl_bytes_rate)*8/1000/1000/1000",
     "legendFormat": "Throughput-G"
    }
   ]
  },
  {
   "title": "dallas_packet_drop",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(dallas_ltt_payload_downlink_packets_dropped_e2e_value+dallas_ltt_payload_uplink_packets_dropped_e2e_value) /(dallas_ltt_payload_gi_dl_packets_value+dallas_ltt_payload_gn_iuu_ul_packets_value)*1e6"
    }
   ]
  },
  {
   "title": "dallas_crash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dallas_system_crashes_value" }
   ]
  },
  {
   "title": "NonRedundantConnection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pcmm_MM_SessionResilienceNonRedundantConnections)",
     "legendFormat": "amf_NonRedundant"
    }
   ]
  },
  {
   "title": "connected_GnodeB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcmm_VS_N2_NbrConnectedGnodeB_5GS"
    }
   ]
  },
  {
   "title": "nf_registration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "NrfInfo_nfstatus{nfServiceName!~\"self\"}",
     "legendFormat": "{{nfType}}({{nfServiceName}})"
    }
   ]
  },
  {
   "title": "PCC_SAU_PDU_PDN_4GBear",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pcmm_VS_MM_NbrActAttachedSub_E)",
     "legendFormat": "4g_sau"
    },
    { "expr": "sum(sgw_nbr_of_bearers)", "legendFormat": "4g_sgw_bearer" },
    {
     "expr": "sum(nbr_of_pgw_pdn_connections)",
     "legendFormat": "4g_pdn"
    },
    {
     "expr": "sum(pcmm_VS_MM_NbrRegisteredSub_5GS{kubernetes_pod_name=~\"eric-pc-mm-mobility.*\"})",
     "legendFormat": "5g_sau"
    },
    {
     "expr": "sum(pdu_session_ipv4{ns=\"1-000002\"}+pdu_session_ipv6{ns=\"1-000002\"}+pdu_session_ipv4v6{ns=\"1-000002\"})",
     "legendFormat": "5g_pdu"
    }
   ]
  },
  {
   "title": "PCG Bearer/session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_up_pfcp_sessions_total", "legendFormat": "pdu" }
   ]
  },
  {
   "title": "eccd1_alert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ALERTS) or vector(0) ", "legendFormat": "eccd1" }
   ]
  },
  {
   "title": "N186_eccd1_active_alarm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dm5gc_alarms{exported_instance=\"N186\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "license-pcc1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-cces1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-ccrc1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-eda1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-ccsm1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-sc1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-ccpc1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-ccdm1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "license-pcg1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "service_id:eric-lm-combiled-server AND message:\"Received report callback\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}