{
 "title": "Dm5gc_CNF_Opensearch_Log",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_datasource", "label": "log_datasource", "query": "elasticsearch" },
   { "name": "severity", "label": "severity", "query": "error,warning,info,debug,WARN" },
   {
    "name": "service_id",
    "label": "service_id",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"service_id.keyword\",\n  \"size\": 200\n} "
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"metadata.pod_name.keyword\",\n  \"size\": 1000\n} "
   },
   {
    "name": "logplane",
    "label": "logplane",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"logplane.keyword\",\n  \"size\": 200\n} "
   },
   { "name": "Filter1", "label": "Filter1" }
  ]
 },
 "panels": [
  {
   "title": "logStatistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "log_per_service_id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "service_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "severity:$severity AND service_id:$service_id AND logplane:$logplane AND metadata.pod_name:$pod_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "logDetail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "log_per_service_id",
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "9999" }, "type": "logs" }
       ],
       "query": "severity:$severity AND service_id:$service_id AND logplane:$logplane AND metadata.pod_name:$pod_name",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "noSeverityLog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "non_error_warning_log_log",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "9999" }, "type": "logs" }
       ],
       "query": "!severity:error AND  !severity:warning AND !severity:info AND !severity:ERROR AND !severity:WARN AND !severity:INFO",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "historyAlarm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "cnf_history_alarm",
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "9999" }, "type": "logs" }
       ],
       "query": "logplane:\"adp-app-asi-logs\" OR logplane:\"adp-app-alarm-log\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "pccISPlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pcc_isp_log",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "9999" }, "type": "logs" }
       ],
       "query": "logplane:\"pcc-isp-log\" OR logplane:\"isp-logs\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}