{
 "title": "PCC dimensioning",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "critical_pod",
    "query": "eric-pc-mm-controller|eric-pc-mm-forwarder|eric-pc-mm-mobility|eric-pc-mm-sctp|eric-pc-vpn-gateway-forwarder|udpforwarder|sgw|nsmfforwarder|http-client|smf|controller|diameter|eric-pc-kvdb-rd-server|ipallocator|eric-pc-sm-geo-red-forwarder|eric-data-object-storage-mn"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "critical pod cpu request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\",container=~\"$critical_pod\"})",
     "legendFormat": "total_request"
    }
   ]
  },
  {
   "title": "critical pod memory request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\",container=~\"$critical_pod\"})",
     "legendFormat": "total_request"
    }
   ]
  },
  {
   "title": "ADP pod CPU request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}) - sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\",container=~\"$critical_pod\"})",
     "legendFormat": "total_request"
    }
   ]
  },
  {
   "title": "ADP pod memory request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}) - sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\",container=~\"$critical_pod\"})",
     "legendFormat": "total_request"
    }
   ]
  }
 ]
}