{
 "title": "Pod_CPU",
 "description": "pod-level-montor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "namespace",
    "label": "kube-namespace",
    "query": {
     "query": "label_values(container_last_seen{}, namespace)"
    }
   },
   { "name": "pod", "label": "custom-parameters", "query": "2" }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",namespace=~\"$namespace\"}[5m]))by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "POD-Restart",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) by(namespace,pod) -sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"} offset 5m) by(namespace,pod)",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Container_CPU_limit",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{namespace=~\"$namespace\",container!=\"\",container!=\"POD\"}/100000"
    }
   ]
  },
  {
   "title": "POD_CPU_limit",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{namespace=~\"$namespace\",container!=\"\",container!=\"POD\"}/100000)by(pod)"
    }
   ]
  },
  {
   "title": "Container-Level-CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{name=~\".+\",namespace=~\"$namespace\",container!=\"POD\",container!=\"init\",pod!=\"\"}[1m])*100",
     "legendFormat": "{{namespace}}-{{pod}}{{container}}"
    }
   ]
  },
  {
   "title": "Container-Level-CPU Usage per Container[with limits ]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " 100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=~\"$namespace\",container!=\"init\",container!~\"search.*\",container!~\"logtransformer.*\",container!~\"logshipper.*\",container!~\"management.*\",container!~\"snmp+alarm.*\",container!~\"sec+key+management.*\"}[1m]))/on(pod,namespace,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=~\"$namespace\",container!=\"init\"})/100000)",
     "legendFormat": "{{namespace}}-{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "POD_LEVEL_CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{name=~\".+\",namespace=~\"$namespace\",container!=\"POD\"}[1m])*100)by(container,pod,namespace)/on(container,pod,namespace)sum(container_spec_cpu_quota{name!=\"\",namespace=~\"$namespace\",container!=\"init\"}/100000)by (container,pod,namespace)",
     "legendFormat": "{{namespace}}-{{pod}}-{{container}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } }
 ]
}