{
 "title": "SCP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SCP Ingress [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(envoy_downstream_rq_xx{group='ingress',envoy_response_code_class='2',nf='scp'}[30s]))/sum(rate(envoy_downstream_rq_total{nf='scp'}[30s]))) * 100",
     "legendFormat": "scp_ingress_success"
    },
    {
     "expr": "(sum(rate(envoy_upstream_rq_xx{envoy_response_code_class='2',nf='scp'}[30s]))/sum(rate(envoy_upstream_rq_total{nf='scp'}[30s]))) * 100",
     "legendFormat": "scp_egress_success"
    }
   ]
  },
  {
   "title": "SCP Requests [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(envoy_downstream_rq_total{nf='scp'}[30s]))",
     "legendFormat": "scp_ingress_mps"
    },
    {
     "expr": "sum(rate(envoy_upstream_rq_total{nf='scp'}[30s]))",
     "legendFormat": "scp_egress_mps"
    }
   ]
  },
  {
   "title": "scp_egress_pool_mps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5,sum(rate(envoy_upstream_rq_total{nf='scp'}[30s])) by (pool_name))",
     "legendFormat": "{{pool_name}}"
    },
    {
     "expr": "topk(5,sum(rate(envoy_upstream_rq_xx{envoy_response_code_class='4',nf='scp'}[30s])) by (pool_name))",
     "legendFormat": "scp_egress_pool_class4_{{pool_name}}"
    },
    {
     "expr": "topk(5,sum(rate(envoy_upstream_rq_xx{envoy_response_code_class='5',nf='scp'}[30s])) by (pool_name))",
     "legendFormat": "scp_egress_pool_class5_{{pool_name}}"
    }
   ]
  },
  {
   "title": "SCP NRF Discovery [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(nrf_in_answers_total{app='eric-scp-manager',nf='scp',status=~'2.*', service='nnrf-disc'}[30s]))/sum(rate(nrf_out_requests_total{app='eric-scp-manager',nf='scp',service='nnrf-disc'}[30s]))) * 100",
     "legendFormat": "scp_nrf_discovery_success"
    },
    {
     "expr": "sum(rate(nrf_out_requests_total{app='eric-scp-manager',nf='scp', service='nnrf-disc', }[30s]))",
     "legendFormat": "scp_nrf_discovery_mps"
    }
   ]
  },
  {
   "title": "SCP Load [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "avg(scp_load)", "legendFormat": "scp_load" }
   ]
  },
  {
   "title": "SCP-Critical-Pod-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc\",container=~\"eric-scp-manager.*|eric-scp-worker.*\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc\"})/100000)",
     "legendFormat": "SCP_{{container}}"
    }
   ]
  },
  {
   "title": "SCP-Critical-Pod-Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc\",container=~\"eric-scp-manager.*|eric-scp-worker.*\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc\",container=~\"eric-scp-manager.*|eric-scp-worker.*\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc\"})*100",
     "legendFormat": "SCP_{{container}}"
    }
   ]
  },
  {
   "title": "SCP-non-Critical-Pod-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc\",container!~\"eric-scp-manager.*|eric-scp-worker.*\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc\"})/100000)",
     "legendFormat": "SCP_{{container}}"
    }
   ]
  },
  {
   "title": "SCP-non-Critical-Pod-Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc\",container!~\"eric-scp-manager.*|eric-scp-worker.*\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc\",container!~\"eric-scp-manager.*|eric-scp-worker.*\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc\"})*100",
     "legendFormat": "SCP_{{container}}"
    }
   ]
  }
 ]
}