global:
  script_path: /root/add_dm_5gc_route.sh
######################################
# Dallas Control System Node
######################################
  cs: []
  
######################################
# Dallas BE Nodes
######################################
  be:
  - interface: em1
    overwrite: true
    routing_instance: sig_cn
    vlan: 1202
    gateway: 172.30.16.1
    node_ips:
    - 172.30.16.101/24
    - 172.30.16.102/24
    static_routes:
    - name: ECFE Signaling Pool
      prefix: 172.17.128.0/24
    - name: ECFE Signaling linknet
      prefix: 172.21.160.0/24

  - interface: em2
    overwrite: true
    routing_instance: ran
    vlan: 1204
    gateway: 172.30.48.1
    node_ips:
    - 172.30.48.101/24,172.30.48.254/32
    - 172.30.48.102/24
    static_routes:
    - name: n280 PCC N2-1/S1-MME-1, N2-2/S1-MME-2
      prefix: 172.16.64.0/24
    - name: n99 PCC N2-1/S1-MME-1, N2-2/S1-MME-2
      prefix: 172.16.72.0/24

  - interface: em2
    overwrite: true
    routing_instance: toExt_open
    vlan: 1205
    gateway: 172.30.64.1
    node_ips:
    - 172.30.64.101/24,172.30.64.254/32
    - 172.30.64.102/24
    static_routes: []

  - interface: em2
    overwrite: true
    routing_instance: ran
    vlan: 1224
    gateway: 172.30.50.1
    node_ips:
    - 172.30.50.101/24
    - 172.30.50.102/24
    static_routes: []

  - interface: em2
    overwrite: true
    routing_instance: toExt_open
    vlan: 1225
    gateway: 172.30.66.1
    node_ips:
    - 172.30.66.101/24
    - 172.30.66.102/24
    static_routes: []

#######################################
## Dallas FE Nodes
#######################################
  fe:
  - interface: p3p1_tap
    overwrite: true
    routing_instance: ran
    vlan: 1204
    cidr: 172.30.48.0/24
    gateway: 172.30.48.1
    node_ips:
    - 172.30.48.201/24
    - 172.30.48.202/24
    static_routes: []

  - interface: p3p1_tap
    overwrite: true
    routing_instance: toExt_open
    vlan: 1205
    cidr: 172.30.64.0/24
    gateway: 172.30.64.1
    node_ips:
    - 172.30.64.201/24
    - 172.30.64.202/24
    static_routes: []

  - interface: p2p1_tap
    overwrite: true
    routing_instance: ran
    vlan: 1224
    cidr: 172.30.50.0/24
    gateway: 172.30.50.1
    node_ips:
    - 172.30.50.201/24
    - 172.30.50.202/24
    static_routes: []

  - interface: p2p1_tap
    overwrite: true
    routing_instance: toExt_open
    vlan: 1225
    cidr: 172.30.66.0/24
    gateway: 172.30.66.1
    node_ips:
    - 172.30.66.201/24
    - 172.30.66.202/24
    static_routes: []
