nodeName: n280-eccd4-pcg1
nodeType: PCG
instance: 1

vnflcm:
  clusterName: n280-eccd4
  namespace: pcg1
#  InstantiateVnfRequest:
#    applicationTimeOut: 1200
#    skipVerification: "true"

users:
  day1:
  - username: pcg-admin
    password: Changeme@1st
    groups: [ system-admin system-troubleshooter ]

ddc:
  remotePath: ddc/n280-eccd4-pcg1

license:
  customerId: '946060'
  swltId: STA-PCG-8
snmp:
  agentEngineId: 800000c104555046a1c1d1
  heartbeatInterval: 600
replicaCount:
  eric-pc-up-data-plane: 12
  eric-pc-up-pfcp-endpoint: 6
  eric-pc-kvdb-rd-server: 3

pcg:
  nicVendor: mellanox
  dpMaxNum: 30
  dpCpu: 16
  nicResrName:
  - intel.com/dp_sriov_mlx5_left
  - intel.com/dp_sriov_mlx5_right
  ipRule:
    ipv4:
      defaultGw: [1]
      bgpNeighbors: [2,3]
      creIpFrom: 21
      dpIpFrom: 31
    ipv6:
      defaultGw: [1]
      bgpNeighbors: [2,3]
      creIpFrom: 21
      dpIpFrom: 31
  intraForward:
    vlan: 2270
    ipv4: 172.21.134.0/24
  networkInstances:
  - name: signaling
    localAs: 4202141002
    remoteAs: 4251100002
    ipForward:
      vlan: 2262
      ipv4: 172.22.38.0/24
    vnfLoop:
      ipv4: 172.18.38.254
    upLoop:
    - name: cp
      ipv4: 172.18.38.1
      interfaces:
      - type: cp-function
        name: sxn4u
      - type: pfcp
        name: sxn4
  - name: internet
    localAs: 4202141005
    remoteAs: 4251100005
    ipForward:
      vlan: 2265
      ipv4: 172.22.134.0/24
      ipv6: fdac:22:128::/64
    dpLoop:
      ipv4: 172.18.134.0/25
      ipv6: fdac:18:128::/64
    vnfLoop:
      ipv4: 172.18.134.254
      ipv6: fdac:18:128::fe
    ipPools:
    - 26.0.0.0/10
    - 26.64.0.0/10
    - fd21:1::/41
    - fd21:1:0200::/41
  - name: ran
    localAs: 4202141004
    remoteAs: 4251100004
    ipForward:
      vlan: 2264
      ipv4: 172.22.70.0/24
    dpLoop:
      ipv4: 172.18.198.0/25
    vnfLoop:
      ipv4: 172.18.198.254
    upLoop:
    - name: access
      ipv4: 172.18.70.0/25
      interfaces:
      - type: access
        name: s1n3
  - name: media
    localAs: 4202141001
    remoteAs: 4251100001
    ipForward:
      vlan: 2261
      ipv4: 172.22.6.0/24
    dpLoop:
      ipv4: 172.18.102.0/25
    vnfLoop:
      ipv4: 172.18.102.254
    upLoop:
    - name: pgw
      ipv4: 172.18.6.0/25
      interfaces:
      - type: access
        name: s5s8u
        default: false
    - name: sgw
      ipv4: 172.18.6.128/25
      interfaces:
      - type: core
        name: s5s8u



