apiVersion: v1
data:
  tap_config.json: |
    [{"ServiceName": "eric-sepp-worker","TAP_ENABLED": false,"TracingMode": "sftp","TAP_INT": "eth0","NF_TYPE": "sepp","TAP_FILTER": "port 443"}]
kind: ConfigMap
metadata:
  name: eric-sc-tap-config

