{
 "title": "BSF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BSF-Reply-Register-successful-Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*sum(rate(bsf_out_answers_total{method=~\"POST\",status=\"201 Created\"}[5m]))by(method) / sum(rate(bsf_in_requests_total{method=~\"POST\"}[5m]))by(method)",
     "legendFormat": "Registrations"
    },
    {
     "expr": "100*sum(rate(bsf_out_answers_total{method=~\"DELETE\",status=\"204 No Content\"}[5m]))by(method)  / sum(rate(bsf_in_requests_total{method=~\"DELETE\"}[5m]))by(method)",
     "legendFormat": "Deregistrations"
    },
    {
     "expr": "100*(sum(rate(bsf_out_answers_total{nf='bsf',status=~'2.*'}[5m])) / sum(rate(bsf_in_requests_total{nf='bsf'}[5m])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "BSF-Reply-Register-unsuccessful-Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(bsf_out_answers_total{method=~\"POST\",status!=\"201 Created\"}[5m])",
     "legendFormat": "{{instance}}_{{method}}_{{status}}"
    },
    {
     "expr": "rate(bsf_out_answers_total{method=~\"DELETE\",status!=\"204 No Content\"}[5m])",
     "legendFormat": "{{instance}}_{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "SC-Critical-Pod-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-diameter.*|eric-bsf-worker.*|eric-stm-diameter.*\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc\"})/100000)",
     "legendFormat": "SC_{{container}}"
    }
   ]
  },
  {
   "title": "SC-non-Critical-Pod-CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-manager.*|eric-cm-mediator.*|eric-cm-yang-provider.*|eric-cnom.*|eric-ctrl-bro.*|eric-data.*|eric-fh.*|eric-lm.*|eric-log.*|eric-odca.*|eric-pm.*|eric-sc.*|eric-sw.*|eric-sec.*|eric-tm.*\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc\"})/100000)",
     "legendFormat": "SC_{{container}}"
    }
   ]
  },
  {
   "title": "SC-Critical-Pod-Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-diameter.*|eric-bsf-worker.*|eric-stm-diameter.*\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-diameter.*|eric-bsf-worker.*|eric-stm-diameter.*\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc\"})*100",
     "legendFormat": "SC_{{container}}"
    }
   ]
  },
  {
   "title": "SC-non-Critical-Pod-Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-manager.*|eric-cm-mediator.*|eric-cm-yang-provider.*|eric-cnom.*|eric-ctrl-bro.*|eric-data.*|eric-fh.*|eric-lm.*|eric-log.*|eric-odca.*|eric-pm.*|eric-sc-hcagent.*|eric-sc-manager.*|eric-stm.*|eric-sec.*|eric-tm.*\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc\",container=~\"eric-bsf-manager.*|eric-cm-mediator.*|eric-cm-yang-provider.*|eric-cnom.*|eric-ctrl-bro.*|eric-data.*|eric-fh.*|eric-lm.*|eric-log.*|eric-odca.*|eric-pm.*|eric-sc-hcagent.*|eric-sc-manager.*|eric-stm.*|eric-sec.*|eric-tm.*\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc\"})*100",
     "legendFormat": "SC_{{container}}"
    }
   ]
  },
  {
   "title": "BSF-discovery-Request-answer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(bsf_in_requests_total{nf='bsf',method=~'GET'})",
     "legendFormat": "Discovery requests"
    },
    {
     "expr": "sum(bsf_out_answers_total{nf='bsf',method=~'GET',status=~'200 OK'})",
     "legendFormat": "Discovery success answers"
    },
    {
     "expr": "sum(bsf_out_answers_total{nf='bsf',method=~'GET',status!='200 OK'})",
     "legendFormat": "Discovery failed answers"
    }
   ]
  },
  {
   "title": "BSF-Delta-Request-number (extrapolated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(bsf_in_requests_total{nf='bsf'}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(bsf_in_requests_total{nf='bsf',method=~'POST'}[1m]))",
     "legendFormat": "Registrations"
    },
    {
     "expr": "sum(increase(bsf_in_requests_total{nf='bsf',method=~'DELETE'}[1m]))",
     "legendFormat": "Deregistrations"
    }
   ]
  },
  {
   "title": "BSF-Offered-Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(bsf_in_requests_total{nf='bsf'}[10s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(bsf_in_requests_total{nf='bsf',method=~'POST'}[10s]))",
     "legendFormat": "Registrations"
    },
    {
     "expr": "sum(rate(bsf_in_requests_total{nf='bsf',method=~'DELETE'}[10s]))",
     "legendFormat": "Deregistrations"
    }
   ]
  },
  {
   "title": "BSF-Delta-Request-number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(bsf_in_requests_total{nf='bsf'}) - sum(bsf_in_requests_total{nf='bsf'} offset 1m)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(bsf_in_requests_total{nf='bsf',method='POST'}) - sum(bsf_in_requests_total{nf='bsf',method='POST'} offset 1m)",
     "legendFormat": "Registrations"
    },
    {
     "expr": "sum(bsf_in_requests_total{nf='bsf',method='DELETE'}) - sum(bsf_in_requests_total{nf='bsf',method='DELETE'} offset 1m)",
     "legendFormat": "Deregistrations"
    }
   ]
  },
  {
   "title": "BSF-PCF-Diameter-request-reject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(Diameter_TransTerm_Ordered{dsl_class='DiaApp',DiaApp='16777236'})",
     "legendFormat": "AF to BSF requests"
    },
    {
     "expr": "sum(Diameter_TransInit_Issued{dsl_class='DiaApp',DiaApp='16777236'})",
     "legendFormat": "BSF to PCF requests"
    },
    {
     "expr": "sum(Diameter_TransInit_Failed{dsl_class='DiaApp',DiaApp='16777236'})",
     "legendFormat": "PCF to BSF rejected"
    },
    {
     "expr": "sum(Diameter_TransTerm_Failed{dsl_class='DiaApp',DiaApp='16777236'})",
     "legendFormat": "BSF to AF rejected"
    }
   ]
  },
  {
   "title": "BSF-HTTP-Discovery-Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(bsf_in_requests_total{nf='bsf',method=~'GET'}[10s])) ",
     "legendFormat": "BSF HTTP [TPS] for discovery"
    },
    {
     "expr": "(sum(rate(bsf_out_answers_total{nf='bsf',method=~'GET',status=~'2.*'}[10s])) / sum(rate(bsf_in_requests_total{nf='bsf',method=~'GET'}[10s]))) * 100",
     "legendFormat": "BSF HTTP Success Rate [%} for discovery"
    }
   ]
  }
 ]
}