{
 "title": "Cluster-Network-Statistics-Host",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(node_network_receive_packets_total{instance=~\"$node\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Packet Rate Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_packets_total{instance=~'$node',device=~\"$interface\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    },
    {
     "expr": "-(irate(node_network_transmit_packets_total{instance=~'$node',device=~\"$interface\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  },
  {
   "title": "TCP Retransmit Segments Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Packet Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(node_network_receive_drop_total{instance=~\"$node\",device=~\"$interface\"}) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}_rx_drop"
    },
    {
     "expr": "(node_network_transmit_drop_total{instance=~\"$node\",device=~\"$interface\"}) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}_{{device}}_tx_drop"
    }
   ]
  },
  {
   "title": "Data Rate Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{instance=~'$node',device=~\"$interface\"}[5m])) * on(instance) group_left(nodename) (node_uname_info) * 8",
     "legendFormat": "{{nodename}}_{{device}}"
    },
    {
     "expr": "-(irate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$interface\"}[5m])) * on(instance) group_left(nodename) (node_uname_info) * 8",
     "legendFormat": "{{nodename}}_{{device}}"
    }
   ]
  }
 ]
}