{
 "title": "Cluster-Disk-IO-Statistics-Container",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_fs_writes_total,namespace)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(container_fs_writes_total,instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{namespace=~\"$namespace\",instance=~\"$host\"}, pod)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(container_fs_writes_total{namespace=~\"$namespace\",instance=~\"$host\",pod=~\"$pod\",container!=\"\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read IOPS per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"$namespace\",pod!=\"\",container!=\"\"}[5m]))by(namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"$namespace\",pod!=\"\",container!=\"\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write IOPS per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"$namespace\",pod!=\"\",container!=\"\"}[5m]))by(namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"$namespace\",pod!=\"\",container!=\"\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Read IOPS per Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{instance=~\"$host\",pod!=\"\",container!=\"\"}[5m]))by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(container_fs_reads_total{instance=~\"$host\",pod!=\"\",container!=\"\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write IOPS per Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{instance=~\"$host\",pod!=\"\",container!=\"\"}[5m]))by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{instance=~\"$host\",pod!=\"\",container!=\"\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Read IOPS per Pod per Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"$namespace\",instance=~\"$host\",pod=~\"$pod\",container!=\"\",device=~\"$device\"}[5m]))by(namespace,pod,instance,device)",
     "legendFormat": "{{namespace}}_{{pod}}_{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "Write IOPS per Pod per Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"$namespace\",instance=~\"$host\",pod=~\"$pod\",container!=\"\",device=~\"$device\"}[5m]))by(namespace,pod,instance,device)",
     "legendFormat": "{{namespace}}_{{pod}}_{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Bytes per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{namespace=~\"$namespace\",instance=~\"$host\",pod=~\"$pod\",container!=\"\"}[5m]))by(namespace,pod,instance,device)",
       "legendFormat": "{{namespace}}_{{pod}}_{{instance}}_{{device}}"
      }
     ]
    },
    {
     "title": "Write Bytes per Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{namespace=~\"$namespace\",instance=~\"$host\",pod=~\"$pod\",container!=\"\"}[5m]))by(namespace,pod,instance,device)",
       "legendFormat": "{{namespace}}_{{pod}}_{{instance}}_{{device}}"
      }
     ]
    }
   ]
  }
 ]
}