{
 "title": "Cluster-Network-Statistics-Pod",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_packets_total, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_network_receive_packets_total{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "ignore_system_ds",
    "query": {
     "query": "label_values(kube_daemonset_labels{namespace=~\"kube-system|monitoring\"},daemonset)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Packet Rate Pod eth0 Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{namespace=~\"$namespace\",pod=~\"$pod\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\",instance=~\"$hostname\"}[5m])",
     "legendFormat": "{{namespace}}_{{pod}}"
    },
    {
     "expr": "-irate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod=~\"$pod\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\",instance=~\"$hostname\"}[5m])",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Packet Rate PCC/PCG secondary interface Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{namespace=~\"$namespace\",pod=~\"eric-pc-mm-forwarder-.*|eric-pc-vpn.*|eric-pc-routing-engine.*\",interface=~\"eth1|net0\",instance=~\"$hostname\"}[5m])",
     "legendFormat": "{{namespace}}_{{pod}}_{{interface}}"
    },
    {
     "expr": "-irate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod=~\"eric-pc-mm-forwarder-.*|eric-pc-vpn.*|eric-pc-routing-engine.*\",interface=~\"eth1|net0\",instance=~\"$hostname\"}[5m])",
     "legendFormat": "{{namespace}}_{{pod}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Data Rate Pod eth0 Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\",instance=~\"$hostname\"}[5m]) * 8",
     "legendFormat": "{{namespace}}_{{pod}}"
    },
    {
     "expr": "-irate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\",instance=~\"$hostname\"}[5m]) * 8",
     "legendFormat": "{{namespace}}_{{pod}}"
    }
   ]
  },
  {
   "title": "Data Rate PCC/PCG secondary interface Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"eric-pc-mm-forwarder-.*|eric-pc-vpn.*|eric-pc-routing-engine.*\",interface=~\"eth1|net0\",instance=~\"$hostname\"}[5m]) * 8",
     "legendFormat": "{{namespace}}_{{pod}}_{{interface}}"
    },
    {
     "expr": "-irate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"eric-pc-mm-forwarder-.*|eric-pc-vpn.*|eric-pc-routing-engine.*\",interface=~\"eth1|net0\",instance=~\"$hostname\"}[5m]) * 8",
     "legendFormat": "{{namespace}}_{{pod}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Packet Rate Pod eth0 Rx/Tx per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"$namespace\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\"}[5m]))by(namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "-sum(irate(container_network_transmit_packets_total{namespace=~\"$namespace\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\"}[5m]))by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Data Rate Pod eth0 Rx/tx per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\"}[5m]))by(namespace) * 8",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "-sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod!~\"$ignore_system_ds.*\",interface=\"eth0\"}[5m]))by(namespace) * 8",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}