{
 "title": "CNF-Traffic-Statistics-CCRC",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "NRF Agent Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nrfagent_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_requests_sent[1m]))by(job,patch,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    }
   ]
  },
  {
   "title": "NRF Traffic Local Site ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nrf_nnrf_nfm_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_requests_recv[1m]))by(operation,remote_endpoint,resource)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_nfm_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_successful_responses_sent[1m]))by(operation,remote_endpoint,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_nfm_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_unsuccessful_responses_sent[1m]))by(operation,remote_endpoint,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_disc_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_disc_requests_recv[1m]))by(operation,remote_endpoint,resource)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_disc_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_disc_successful_responses_sent[1m]))by(operation,remote_endpoint,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_disc_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_disc_unsuccessful_responses_sent[1m]))by(operation,remote_endpoint,resource,status_code)"
      }
     ]
    }
   ]
  },
  {
   "title": "NRF Traffic Remote Site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nrf_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_requests_sent[1m]))by(operation,remote_endpoint,resource)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_successful_responses_recv[1m]))by(operation,remote_endpoint,resource)"
      }
     ]
    },
    {
     "title": "eric_nrf_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrf_nnrf_nfm_unsuccessful_responses_recv[1m]))by(operation,remote_endpoint,resource)"
      }
     ]
    }
   ]
  },
  {
   "title": "NSSF Traffic Local Site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nssf_nnssf_nsselection_requests_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(irate(eric_nssf_nnssf_nsselection_requests_recv[1m]))by(operation,query_type,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nssf_nnssf_nsselection_successful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "sum(irate(eric_nssf_nnssf_nsselection_successful_responses_sent[1m]))by(operation,query_type,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nssf_nnssf_nsselection_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "sum(irate(eric_nssf_nnssf_nsselection_unsuccessful_responses_sent[1m]))by(operation,query_type,remote_endpoint,req_info,resource)"
      }
     ]
    }
   ]
  }
 ]
}