{
 "title": "CNF-Traffic-Statistics-CCDM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "NRF Agent Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_nrfagent_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_requests_sent[1m]))by(job,patch,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    }
   ]
  },
  {
   "title": "UDR Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_udr_nudr_dr_requests_recv_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_requests_recv_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_dr_successful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_successful_responses_sent_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_dr_unsuccessful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_unsuccessful_responses_sent_total[1m]))by(job,operation,req_info,resource,serviceId,status_code)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}} {{status_code}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_dr_requests_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_requests_sent_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_dr_successful_responses_recv_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_successful_responses_recv_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_dr_unsuccessful_responses_recv_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_dr_unsuccessful_responses_recv_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} ({{req_info}}) {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_ncudr_gud_dr_requests_recv_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ncudr_gud_dr_requests_recv_total[1m]))by(job,operation,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_ncudr_gud_dr_successful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ncudr_gud_dr_successful_responses_sent_total[1m]))by(job,operation,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_ncudr_gud_dr_unsuccessful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_ncudr_gud_dr_unsuccessful_responses_sent_total[1m]))by(job,operation,resource,serviceId,status_code)",
       "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Provisioning Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric_udr_nudr_prov_requests_recv_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_prov_requests_recv_total[1m]))by(job,operation,req_info,resource,serviceId)",
       "legendFormat": "{{job}} {{operation}} {{req_info}} {{resource}} {{serviceId}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_prov_successful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_prov_successful_responses_sent_total[1m]))by(job,operation,req_info,resource,serviceId,status_code)",
       "legendFormat": "{{job}} {{operation}} {{req_info}} {{resource}} {{serviceId}} {{status_code}}"
      }
     ]
    },
    {
     "title": "eric_udr_nudr_prov_unsuccessful_responses_sent_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(eric_udr_nudr_prov_unsuccessful_responses_sent_total[1m]))by(job,operation,req_info,resource,serviceId,status_code)",
       "legendFormat": "{{job}} {{operation}} {{req_info}} {{resource}} {{serviceId}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Subscription Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "eric_udr_app_counter_5g_predefined_counters_5gactsubin",
       "legendFormat": "Number of MSISDNs stored in UDR that includes 5G location information"
      },
      {
       "expr": "eric_udr_app_counter_5g_predefined_counters_5gsubin",
       "legendFormat": "Number of 5G users with UDM subscription"
      },
      {
       "expr": "eric_udr_app_counter_5g_predefined_counters_5gsupi",
       "legendFormat": "Number of SUPIs stored in UDR that includes 5G authentication data"
      },
      {
       "expr": "eric_udr_app_counter_5g_predefined_counters_pcfsubnbr",
       "legendFormat": "Number of 5G users with PCF subscription"
      }
     ]
    }
   ]
  }
 ]
}