{
 "title": "CNF-Traffic-Statistics-CCPC",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "CCPC POD Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CCPC Pods Average CPU Usage per Container [limits]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccpc1\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"}))by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CCPC Pods CPU Usage per Container [limits]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"ccpc1\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"})",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "CCPC Pods Average Memory Usage per Container [limits]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100)by(container)",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "CCPC Pods Memory Usage per Container [limits]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100",
     "legendFormat": "{{pod}}-{{container}} "
    }
   ]
  },
  {
   "title": "Pod_Container_Restart_Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"ccpc1\"}",
     "legendFormat": "{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "N280_eccd1_active_alarm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dm5gc_alarms{exported_instance=\"N280\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CCPC Provisioning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCPC_Provisioning_counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum(irate(eric_ccpc_provisioning_requests_recv[5m]))",
       "legendFormat": "ccpc_provisioning_requests_recv"
      },
      {
       "expr": "sum(irate(eric_ccpc_provisioning_successful_responses_sent[5m]))",
       "legendFormat": "ccpc_provisioning_successful_responses_sent"
      }
     ]
    }
   ]
  },
  {
   "title": "NRF Agent Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "eric_nrfagent_nnrf_nfm_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_requests_sent[1m]))by(job,patch,operation,remote_endpoint,req_info,resource)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "targets": [
      {
       "expr": "sum(irate(eric_nrfagent_nnrf_nfm_unsuccessful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)"
      }
     ]
    },
    {
     "title": "nrfagent_nnrf_disc_requests_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "\r\nsum(irate(eric_nrfagent_nnrf_disc_requests_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)",
       "legendFormat": "{{req_info}}-{{resource}}"
      }
     ]
    },
    {
     "title": "nrfagent_nnrf_disc_successful_responses_recv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\r\nsum(irate(eric_nrfagent_nnrf_disc_successful_responses_recv[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)",
       "legendFormat": "{{req_info}}-{{resource}}"
      }
     ]
    },
    {
     "title": "eric_nrfagent_discovery_unsuccessful_responses_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\r\nsum(irate(eric_nrfagent_discovery_unsuccessful_responses_sent[1m]))by(job,operation,remote_endpoint,req_info,resource,status_code)",
       "legendFormat": "{{req_info}}-{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCF Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "eric_pcf_rx_interface_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_rx_requests_recv[1m]))",
     "legendFormat": "eric_pcf_rx_requests_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_rx_requests_unsent[1m]))",
     "legendFormat": "eric_pcf_rx_requests_unsent"
    },
    {
     "expr": "sum(irate(eric_pcf_rx_unsuccessful_responses_sent[1m]))",
     "legendFormat": "eric_pcf_rx_unsuccessful_responses_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_rx_unsuccessful_responses_recv[1m]))",
     "legendFormat": "eric_pcf_rx_unsuccessful_responses_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_rx_successful_responses_sent[1m]))",
     "legendFormat": "eric_pcf_rx_successful_responses_sent"
    }
   ]
  },
  {
   "title": "eric_pcf_rx_interface_successful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(eric_pcf_rx_successful_responses_sent[1m])) / sum(rate(eric_pcf_rx_requests_recv[1m]))) * 100",
     "legendFormat": "eric_pcf_rx_interface_successful_ratio"
    }
   ]
  },
  {
   "title": "pcf_rx_unsuccessful_responses_sent&recv_total:ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "remote_endpoint:eric_pcf_rx_unsuccessful_responses_recv_total:ratio",
     "legendFormat": "pcf_rx_unsuccessful_responses_recv_total:ratio"
    },
    {
     "expr": "remote_endpoint:eric_pcf_rx_unsuccessful_responses_sent_total:ratio",
     "legendFormat": "pcf_rx_unsuccessful_responses_sent_total:ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_rx_overload_unsuccessful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum:eric_pcf_rx_overload_unsuccessful_ratio:rate",
     "legendFormat": "eric_pcf_rx_overload_unsuccessful_ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_rx_unsuccessful_status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_rx_unsuccessful_responses_recv[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    },
    {
     "expr": "sum(irate(eric_pcf_rx_unsuccessful_responses_sent[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    }
   ]
  },
  {
   "title": "eric_pcf_gx_interface_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_gx_requests_sent[1m]))",
     "legendFormat": "eric_pcf_gx_requests_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_requests_recv[1m]))",
     "legendFormat": "eric_pcf_gx_requests_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_requests_recv_usage_limit_surpassed[1m]))",
     "legendFormat": "eric_pcf_gx_requests_recv_usage_limit_surpassed"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_requests_unsent[1m]))",
     "legendFormat": "eric_pcf_gx_requests_unsent"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_successful_responses_recv[1m]))",
     "legendFormat": "eric_pcf_gx_successful_responses_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_successful_responses_sent[1m]))",
     "legendFormat": "eric_pcf_gx_successful_responses_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_unsuccessful_responses_recv[1m]))",
     "legendFormat": "eric_pcf_gx_unsuccessful_responses_recv"
    },
    {
     "legendFormat": "eric_pcf_gx_unsuccessful_responses_recv"
    }
   ]
  },
  {
   "title": "pcf_gx_unsuccessful_responses_sent&recv_total:ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "remote_endpoint:eric_pcf_gx_unsuccessful_responses_recv_total:ratio",
     "legendFormat": "pcf_gx_unsuccessful_responses_recv_total:ratio"
    },
    {
     "expr": "remote_endpoint:eric_pcf_gx_unsuccessful_responses_sent_total:ratio",
     "legendFormat": "pcf_gx_unsuccessful_responses_sent_total:ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_gx_successful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(eric_pcf_gx_successful_responses_recv[1m])) / sum(rate(eric_pcf_gx_requests_sent[1m]))) * 100",
     "legendFormat": "eric_pcf_gx_successful_responses_recv_ratio"
    },
    {
     "expr": "(sum(rate(eric_pcf_gx_successful_responses_sent[1m]))/sum(rate(eric_pcf_gx_requests_recv[1m]))) * 100",
     "legendFormat": "eric_pcf_gx_successful_responses_sent_ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_gx_overload_unsuccessful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum:eric_pcf_gx_overload_unsuccessful_ratio:rate",
     "legendFormat": "eric_pcf_gx_overload_unsuccessful_ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_gx_unsuccessful_status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_gx_unsuccessful_responses_recv[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    },
    {
     "expr": "sum(irate(eric_pcf_gx_unsuccessful_responses_sent[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    }
   ]
  },
  {
   "title": "N7_eric_pcf_npcf_smpolicycontrol_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_requests_sent[1m]))",
     "legendFormat": "smpolicycontrol_requests_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_requests_recv[1m]))",
     "legendFormat": "smpolicycontrol_requests_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_requests_unsent[1m]))",
     "legendFormat": "smpolicycontrol_requests_unsent"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_successful_responses_recv[1m]))",
     "legendFormat": "smpolicycontrol_successful_responses_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_successful_responses_sent[1m]))",
     "legendFormat": "smpolicycontrol_successful_responses_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_recv[1m]))",
     "legendFormat": "smpolicycontrol_unsuccessful_responses_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_sent[1m]))",
     "legendFormat": "smpolicycontrol_unsuccessful_responses_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_requests_recv_usage_limit_surpassed[1m]))",
     "legendFormat": "smpolicycontrol_requests_recv_usage_limit_surpassed"
    }
   ]
  },
  {
   "title": "N7_smpolicycontrol_successful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(eric_pcf_npcf_smpolicycontrol_successful_responses_sent[1m])) / sum(rate(eric_pcf_npcf_smpolicycontrol_requests_recv[1m]))) * 100",
     "legendFormat": "smpolicycontrol_successful_responses_sent_ratio"
    },
    {
     "expr": "(sum(rate(eric_pcf_npcf_smpolicycontrol_successful_responses_recv[1m])) / sum(rate(eric_pcf_npcf_smpolicycontrol_requests_sent[1m]))) * 100",
     "legendFormat": "smpolicycontrol_successful_responses_recv_ratio"
    }
   ]
  },
  {
   "title": "N7_smpolicycontrol_unsuccessful_responses_send&recv_total:ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "remote_endpoint:eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_sent_total:ratio",
     "legendFormat": "smpolicycontrol_unsuccessful_responses_sent_total:ratio"
    },
    {
     "expr": "remote_endpoint:eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_recv_total:ratio",
     "legendFormat": "smpolicycontrol_unsuccessful_responses_recv_total:ratio"
    }
   ]
  },
  {
   "title": "N7_pcf_npcf_smpolicycontrol_unsuccessful_status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_recv[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    },
    {
     "expr": "sum(irate(eric_pcf_npcf_smpolicycontrol_unsuccessful_responses_sent[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    }
   ]
  },
  {
   "title": "N36_eric_pcf_nudr_dr_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_requests_sent[1m]))",
     "legendFormat": "eric_pcf_nudr_dr_requests_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_requests_recv[1m]))",
     "legendFormat": "eric_pcf_nudr_dr_requests_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_successful_responses_recv[1m]))",
     "legendFormat": "eric_pcf_nudr_dr_successful_responses_recv"
    },
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_successful_responses_sent[1m]))",
     "legendFormat": "eric_pcf_nudr_dr_successful_responses_sent"
    },
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_unsuccessful_responses_sent[1m]))",
     "legendFormat": "eric_pcf_nudr_dr_unsuccessful_responses_sent"
    }
   ]
  },
  {
   "title": "N36_pcf_nudr_dr_successful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(eric_pcf_nudr_dr_successful_responses_sent[1m])) / sum(rate(eric_pcf_nudr_dr_requests_recv[1m]))) * 100",
     "legendFormat": "pcf_nudr_dr_successful_responses_sent_ratio"
    },
    {
     "expr": "(sum(rate(eric_pcf_nudr_dr_successful_responses_recv[1m])) / sum(rate(eric_pcf_nudr_dr_requests_sent[1m]))) * 100",
     "legendFormat": "pcf_nudr_dr_successful_responses_recv_ratio"
    }
   ]
  },
  {
   "title": "N36_nudr_dr_unsuccessful_responses_recv_total:ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "remote_endpoint:eric_pcf_nudr_dr_unsuccessful_responses_recv_total:ratio",
     "legendFormat": "nudr_dr_unsuccessful_responses_recv_total:ratio"
    },
    {
     "legendFormat": "pcf_nudr_dr_successful_responses_recv_ratio"
    }
   ]
  },
  {
   "title": "N36_eric_pcf_nudr_dr_unsuccessful_status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_unsuccessful_responses_recv[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    },
    {
     "expr": "sum(irate(eric_pcf_nudr_dr_unsuccessful_responses_sent[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    }
   ]
  },
  {
   "title": "nbsf_management_counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(eric_pcf_nbsf_management_requests_sent[1m]))",
     "legendFormat": "nbsf_management_requests_sent"
    },
    {
     "expr": "sum(rate(eric_pcf_nbsf_management_successful_responses_recv[1m]))",
     "legendFormat": "nbsf_management_successful_responses_rec"
    },
    {
     "expr": "sum(rate(eric_pcf_nbsf_management_unsuccessful_responses_recv[1m]))",
     "legendFormat": "nbsf_management_unsuccessful_responses_recv"
    }
   ]
  },
  {
   "title": "nbsf_management_unsuccessful_responses_recv_total:ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "remote_endpoint:eric_pcf_nbsf_management_unsuccessful_responses_recv_total:ratio",
     "legendFormat": "nbsf_management_unsuccessful_responses_recv_total:ratio"
    }
   ]
  },
  {
   "title": "nbsf_management_successful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(eric_pcf_nbsf_management_successful_responses_recv[1m])) / sum(rate(eric_pcf_nbsf_management_requests_sent[1m])) * 100",
     "legendFormat": "nbsf_management_successful_ratio"
    }
   ]
  },
  {
   "title": "eric_pcf_nbsf_management_unsuccessful_status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(eric_pcf_nbsf_management_unsuccessful_responses_recv[1m]))by(job,operation,resource,serviceId,status_code)",
     "legendFormat": "{{job}} {{operation}} {{resource}} {{serviceId}} {{status_code}}"
    }
   ]
  },
  {
   "title": "eric_ccpc_aspect_bsfegressproxy_overload_unsuccessful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum:eric_ccpc_aspect_bsfegressproxy_overload_unsuccessful_ratio:rate",
     "legendFormat": "ccpc_aspect_bsfegressproxy_overload_unsuccessful_ratio"
    }
   ]
  },
  {
   "title": "eric_ccpc_aspect_udregressproxy_overload_unsuccessful_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum:eric_ccpc_aspect_udregressproxy_overload_unsuccessful_ratio:rate",
     "legendFormat": "ccpc_aspect_udregressproxy_overload_unsuccessful_ratio"
    }
   ]
  }
 ]
}