{
 "title": "Dm5gc-Disk-Storage-Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "k8s_disk_latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total[10m]) / irate(node_disk_writes_completed_total[10m])* on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "-irate(node_disk_read_time_seconds_total[10m]) / irate(node_disk_reads_completed_total[10m])* on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "k8s_disk_IOPs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " -irate(node_disk_reads_completed_total[30m])* on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "read_{{nodename}}_{{device}}"
    },
    {
     "expr": " irate(node_disk_writes_completed_total[30m])* on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "write_{{nodename}}_{{device}}"
    }
   ]
  },
  {
   "title": "pvc_usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes)*100",
     "legendFormat": "{{instance}}({{namespace}}){{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PV and PVC status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase) by (phase)",
     "legendFormat": "PV_status_{{phase}}"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "PVC_status_{{phase}}"
    }
   ]
  },
  {
   "title": "storage_operation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storage_operation_duration_seconds_sum[5m]) / rate(storage_operation_duration_seconds_count[5m])",
     "legendFormat": "{{instance}}_{{operation_name}}"
    }
   ]
  }
 ]
}