{
 "title": "Dm5gc_K8s_Overall_Status",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "clusterStatus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "node_status_in_ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"})",
     "legendFormat": "{{condition}}"
    },
    {}
   ]
  },
  {
   "title": "kube_node_role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_role) by (role)", "legendFormat": "{{role}}" }
   ]
  },
  {
   "title": "node_status_condition",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition!=\"Ready\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "node_unschedulable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "namespace_per_status_phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase) by (phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "top_pvc_disk_utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes/ kubelet_volume_stats_capacity_bytes * 100 > 70",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ephemeral_requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"ephemeral_storage\"}) /1024 /1024 /1024"
    }
   ]
  },
  {
   "title": "ephemeral_limites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"ephemeral_storage\"}) /1024 /1024 /1024"
    }
   ]
  },
  {
   "title": "std_node_cpu",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node=~\".*pool1.*\"})"
    }
   ]
  },
  {
   "title": "std_cpu_requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\".*pool1.*\"})"
    }
   ]
  },
  {
   "title": "std_cpu_limites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node=~\".*pool1.*\"})"
    }
   ]
  },
  {
   "title": "std_max_occupied_cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\".*pool1.*\"}) by (node))"
    }
   ]
  },
  {
   "title": "std_max_empty_cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_node_status_capacity{resource=\"cpu\",node=~\".*pool1.*\"}) by (node) - sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\".*pool1.*\"}) by (node))"
    }
   ]
  },
  {
   "title": "top_node_disk_utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2,node_disk_utilization_record)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "pvc_status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "pv_status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "max_disk_latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "max((irate(node_disk_write_time_seconds_total[10m]) / irate(node_disk_writes_completed_total[10m])* on(instance) group_left(nodename) (node_uname_info)))",
     "legendFormat": "write_latency"
    },
    {
     "expr": "-max((irate(node_disk_read_time_seconds_total[10m]) / irate(node_disk_reads_completed_total[10m])* on(instance) group_left(nodename) (node_uname_info)))",
     "legendFormat": "read_latency"
    }
   ]
  },
  {
   "title": "license_status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(license_consumer_license_status) by (license_status)",
     "legendFormat": "{{license_status}}"
    }
   ]
  },
  {
   "title": "license_connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(license_consumer_connection_state) by (connection_state)",
     "legendFormat": "{{connection_state}}"
    }
   ]
  },
  {
   "title": "kube_api_health",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "targets": [
    { "expr": "sum(kube_api_health_state)", "legendFormat": "state_in_period" }
   ]
  },
  {
   "title": "etcd_leader_change",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "irate(etcd_server_leader_changes_seen_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "etcd_active_alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etcd_active_alarms" }
   ]
  },
  {
   "title": "etcd_member_started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etcd_member_started", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "etcd_network_peer_rtt",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_round_trip_time_seconds_sum[1m]) / rate(etcd_network_peer_round_trip_time_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "statefulset_spec_vs_ready",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_replicas) by (namespace) - sum(kube_statefulset_status_replicas_ready) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "deployment_spec_vs_ready",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "(sum(kube_deployment_spec_replicas) by (namespace)) - (sum(kube_deployment_status_replicas_ready) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "endpoint_not_ready",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(kube_endpoint_address_not_ready[2m]) > 0",
     "legendFormat": "{{namespace}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "pod_status_by_phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase @ end()) by (phase) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)"
    }
   ]
  },
  {
   "title": "std_node_network_pkts_in_K",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_packets_total[5m]) * on(instance) group_left(nodename) (node_uname_info{nodename=~\".*pool1.*\"})) /1000",
     "legendFormat": "sent_pkts"
    },
    {
     "expr": "-sum(irate(node_network_receive_packets_total[5m]) * on(instance) group_left(nodename) (node_uname_info{nodename=~\".*pool1.*\"})) /1000",
     "legendFormat": "receive_pkts"
    }
   ]
  },
  {
   "title": "std_node_network_error_drop_pkts_in_K",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_drop_total+node_network_transmit_errs_total[5m]) * on(instance) group_left(nodename) (node_uname_info{nodename=~\".*pool.*\"})) /1000",
     "legendFormat": "sent_error_pkts"
    },
    {
     "expr": "-sum(irate(node_network_receive_drop_total+node_network_receive_errs_total[5m]) * on(instance) group_left(nodename) (node_uname_info{nodename=~\".*pool.*\"})) /1000",
     "legendFormat": "receive_error_pkts"
    }
   ]
  },
  {
   "title": "container_cpu_throttled",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container!=\"\"}[5m]))  by (container,namespace)",
     "legendFormat": "{{namespace}}_{{container}}"
    }
   ]
  },
  {
   "title": "node_cpu_record",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "node_cpu_record * on(instance) group_left(nodename) (node_uname_info{nodename!~\".*pool3.*\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "node_load1",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "node_load1 * on(instance) group_left(nodename) (node_uname_info{nodename!~\".*pool3.*\"})"
    }
   ]
  },
  {
   "title": "node_memory_record",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "node_memory_record * on(instance) group_left(nodename) (node_uname_info{nodename!~\".*pool3.*\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "ecfe_bfd",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(ecfe_speaker_peer_flapping_indicator)",
     "legendFormat": "flap"
    },
    {
     "expr": "sum(ecfe_speaker_bfd_sessions_not_up)",
     "legendFormat": "not_up"
    },
    {
     "expr": "sum(ecfe_speaker_bfd_sessions_up)",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "upf_bfd",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(pc_up_bfd_sessions) by (type) > 0",
     "legendFormat": "total_session"
    },
    {
     "expr": "sum(rate(pc_up_bfd_removed_sessions_total[2m])) by (type)",
     "legendFormat": "removed_session"
    },
    {
     "expr": "sum(rate(pc_up_bfd_created_sessions_total[2m])) by (type)",
     "legendFormat": "created_session"
    }
   ]
  },
  {
   "title": "container&HPA status change",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "hpa_replicas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\"}",
       "legendFormat": "{{namespace}}_{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "kube_pod_container_status_running-change",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{container!~\".*cm-init.*\",pod!~\".*curator.*\",container!~\".*job.*\",container!~\".*loader.*\",container!~\".*init.*\", container!~\".*cmproxy.*\", container!~\"cm-schema-import\",container!~\".*restarter\",container!~\"eric-sw-inventory-manager\"}) by (namespace) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "kube_pod_container_terminated_reason",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_last_terminated_reason{reason!=\"Completed\"}) by (namespace,reason)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_restart",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{container!~\".*cm-init.*\",pod!~\".*curator.*\",container!~\".*job.*\",container!~\".*loader.*\",container!~\".*init.*\", container!~\".*cmproxy.*\", container!~\"cm-schema-import\",container!~\".*restarter\",container!~\"eric-sw-inventory-manager\",namespace=\"$namespace\"}[1m])  >0",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "container_terminated",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "kube_pod_container_status_terminated{namespace=\"$namespace\"} ",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "resource_per_namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_requests_per_namespace",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "memory_requests_per_namespace",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "accG" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace) / 1000 / 1000 / 1000",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "storage_requests_per_namespace",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "accG" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"ephemeral_storage\"}) by (namespace) / 1000 / 1000 / 1000",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}