{
 "title": "EVNFM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "System-CPU-Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{app_kubernetes_io_managed_by!=\"Helm\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "ElasticSearch-CPU-Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pod_Container_Memory_Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=\"evnfm1\"} - container_memory_cache{namespace=\"evnfm1\"}) / on(namespace,pod,container)group_left() kube_pod_container_resource_limits{namespace=\"evnfm1\",resource=\"memory\"}",
     "legendFormat": "{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Node_Memory_Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_memory_record", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "PM-Server-Volume-Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "expr": "pms_volume_stats_used_bytes{} /1024/1024/1024",
     "legendFormat": "Used_{{instance}}_{{persistentvolumeclaim}}"
    },
    {
     "expr": "pms_volume_stats_capacity_bytes{} /1024/1024/1024",
     "legendFormat": "Capacity_{{instance}}_{{persistentvolumeclaim}}"
    },
    {
     "expr": "pms_volume_stats_available_bytes{} /1024/1024/1024",
     "legendFormat": "Available_{{instance}}_{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "POD Disk Usage Under The Path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(disk_total_bytes - disk_free_bytes ) / disk_total_bytes",
     "legendFormat": " {{app}} {{kubernetes_pod_name}} {{path}}"
    }
   ]
  },
  {
   "title": "PG_Data_Volume_Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_volume_stats_used_bytes / pg_volume_stats_capacity_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Bro_Data_Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bro_volume_stats_used_bytes / bro_volume_stats_capacity_bytes",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pod_Container_Restart_Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"evnfm1\"}",
     "legendFormat": "{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "POD_Process_Quantity_Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_processes{namespace=\"evnfm1\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP_Server_Requests_2xx_3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app!=\"eric-eo-evnfm-crypto\",app_kubernetes_io_managed_by!=\"Helm\",status=~\"2.*|3.*\"}[5m])) by (status,app,outcome,method)",
     "legendFormat": "{{outcome}}{{status}}_{{app}}_{{method}}"
    }
   ]
  },
  {
   "title": "HTTP_Client_Requests_2xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{status=~\"2.*\",clientName!=\"localhost\"}[5m]) > 0",
     "legendFormat": "{{outcome}}{{status}}_{{clientName}}/{{method}}/{{uri}}"
    }
   ]
  },
  {
   "title": "Registry-HTTP-Requests-2XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "irate(registry_http_requests_total{code=~\"2.*\"}[5m]) >0",
     "legendFormat": "{{code}}_{{kubernetes_name}}_{{method}}"
    }
   ]
  },
  {
   "title": "HTTP_Server_Requests_Non_2xx_3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app!=\"eric-eo-evnfm-crypto\",app_kubernetes_io_managed_by!=\"Helm\",status!~\"2.*|3.*\"}[5m])) by (status,app,outcome,method) > 0",
     "legendFormat": "{{outcome}}{{status}}_{{app}}_{{method}}"
    }
   ]
  },
  {
   "title": "Registry-HTTP-Requests-non-2XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "irate(registry_http_requests_total{code!~\"2.*\"}[5m]) >0",
     "legendFormat": "{{code}}_{{kubernetes_name}}_{{method}}"
    }
   ]
  },
  {
   "title": "HTTP_Client_Requests_Non_2xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{status!~\"2.*\",clientName!=\"localhost\"}[5m]) > 0",
     "legendFormat": "{{outcome}}{{status}}_{{clientName}}/{{method}}/{{uri}}"
    }
   ]
  }
 ]
}