{
 "title": "Dm5gc-CNF-CPU-Memory-Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pcc_critical_pod",
    "label": "pcc_critical_pod",
    "query": "eric-pc-mm-controller|eric-pc-mm-forwarder|eric-pc-mm-mobility|eric-pc-mm-sctp|eric-pc-vpn-gateway-forwarder|udpforwarder|sgw|nsmfforwarder|http-client|smf|controller|diameter|eric-pc-kvdb-rd-server|ipallocator|eric-pc-sm-geo-red-forwarder|eric-data-object-storage-mn"
   },
   {
    "name": "pcg_critical_pod",
    "label": "pcg_critical_pod",
    "query": "eric-pc-kvdb-rd-server|eric-pc-up-pfcp-endpoint|eric-pc-routing-engine-api|eric-data-object-storage-mn"
   },
   {
    "name": "ccrc_critical_pod",
    "label": "ccrc_critical_pod",
    "query": "eric-nrf-management|eric-nrf-discovery|eric-nrf-management-notification|eric-nssf-slice-selection-control|eric-nssf-nssai-availability|eric-nrf-kvdb-ag-locator|eric-nrf-kvdb-ag-server|eric-nssf-kvdb-ag-locator|eric-nssf-kvdb-ag-server"
   },
   {
    "name": "ccsm_critical_pod",
    "label": "ccsm_critical_pod",
    "query": "eric-ausf-engine|eric-eir-eireic|eric-eir-socshipper|eric-hssepc-s6adiameter|eric-hssepc-s6aauthentication|eric-hssepc-s6aupdatelocation|eric-hssepc-subscriptionupdate|eric-hss-redisdb|eric-stm-diameter|eric-udm-epsauth|eric-udm-sdmamdata|eric-udm-sdmnssai|eric-udm-sdmsmdata|eric-udm-sdmsmfselect|eric-udm-sdmsubscriptions|eric-udm-ueauth|eric-udm-uecmamfget|eric-udm-uecmreg|eric-udm-uecmsmfderegistration|eric-udm-uecmsmfregistration"
   },
   {
    "name": "ccdm_critical_pod",
    "label": "ccdm_critical_pod",
    "query": "eric-udr-gudrestfe|eric-udr-gudrestfe|eric-udr-ldapfe|eric-udr-nudrfe|eric-udr-query-router|eric-udr-http-proxy|eric-udr-kvdb-ag-locator|eric-udr-kvdb-ag-server|eric-udr-notificationsubscription|eric-udr-provisioningfe"
   },
   {
    "name": "cces_critical_pod",
    "label": "cces_critical_pod",
    "query": "eric-apigm-api-proxy|eric-nef-afsessionwithqos-provisioning|eric-nef-afsessionwithqos|diameter|diameterproxygrpc|dced|cassandra"
   },
   {
    "name": "scp_critical_pod",
    "label": "scp_critical_pod",
    "query": "eric-scp-manager.*|eric-scp-worker.*|diameter|cassandra"
   },
   {
    "name": "bsf_critical_pod",
    "label": "bsf_critical_pod",
    "query": "eric-bsf-diameter.*|eric-bsf-worker.*|eric-stm-diameter.*|bsfdiameter|cassandra"
   },
   {
    "name": "ccpc_critical_pod",
    "label": "ccpc_critical_pod",
    "query": "diameter|eric-ccpc-data-access|eric-ingressgw-pcf-traffic|eric-pcf-dms-locator|eric-pcf-dms-server|eric-pcf-egress-proxy|eric-pcf-egress-proxy-bsf|eric-pcf-license-handler|eric-pcf-rx-policy-control|eric-pcf-session-management-policy-control|eric-pcrf-ipcan-session-management|eric-stm-diameter"
   }
  ]
 },
 "panels": [
  {
   "title": "PCC CPU Memory PMRM ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCC_Critical_Pod_CPU_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_cpu_usage_percent{container=~\"$pcc_critical_pod\"}) by (container)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_CPU_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_cpu_usage_percent{container=~\"$pcc_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_percent{container=~\"$pcc_critical_pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_Memory_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_mem_usage_percent{container=~\"$pcc_critical_pod\"}) by (container)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_Memory_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_mem_usage_percent{container=~\"$pcc_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_Memory_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_percent{container=~\"$pcc_critical_pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Non_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_percent{container!~\"$pcc_critical_pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Non_Critical_Pod_Memory_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_percent{container!~\"$pcc_critical_pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCG CPU Memory PMRM ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCG_UP_CPU_Load_Peak_Ingress",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pc_up_cpu_load_15s_peak_percent{role=\"Ingress\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "PCG_UP_CPU_Load_Peak_Egress",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pc_up_cpu_load_15s_peak_percent{role=\"Egress\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_CPU_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_cpu_usage_percent{container=~\"$pcg_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_CPU_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(pmrm_container_cpu_usage_percent{container=~\"$pcg_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_percent{container=~\"$pcg_critical_pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_Memory_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_mem_usage_percent{container=~\"$pcg_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_Memory_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(pmrm_container_mem_usage_percent{container=~\"$pcg_critical_pod\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_Memory_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(pmrm_container_mem_usage_percent{container=~\"$pcg_critical_pod\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCG_Non_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_percent{container!~\"$pcg_critical_pod\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Non_Critical_Pod_Memory_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_percent{container!~\"$pcg_critical_pod\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCRC CPU Memory PMRM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCRC_Critical_Pod_CPU_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg(pmrm_container_cpu_usage_nanocore{container=~\"$ccrc_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccrc_critical_pod\"}) by (container)) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC_Critical_Pod_CPU_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_cpu_usage_nanocore{container=~\"$ccrc_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccrc_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container=~\"$ccrc_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccrc_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCRC_Critical_Pod_Mem_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_mem_usage_bytes{container=~\"$ccrc_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccrc_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC_Critical_Pod_Mem_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_mem_usage_bytes{container=~\"$ccrc_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccrc_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC_Critical_Pod_Mem_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container=~\"$ccrc_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccrc_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCRC_Non_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container!~\"$ccrc_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container!~\"$ccrc_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCRC_Non_Critical_Pod_Mem_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container!~\"$ccrc_critical_pod\"} / pmrm_container_mem_limits_bytes{container!~\"$ccrc_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCDM CPU Memory PMRM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCDM_Critical_Pod_CPU_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_cpu_usage_nanocore{container=~\"$ccdm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccdm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM_Critical_Pod_CPU_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_cpu_usage_nanocore{container=~\"$ccdm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccdm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container=~\"$ccdm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccdm_critical_pod\"} * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM_Critical_Pod_Mem_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_mem_usage_bytes{container=~\"$ccdm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccdm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM_Critical_Pod_Mem_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_mem_usage_bytes{container=~\"$ccdm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccdm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM_Critical_Pod_Mem_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container=~\"$ccdm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccdm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCDM_Non_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container!~\"$ccdm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container!~\"$ccdm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCDM_Non_Critical_Pod_Mem_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container!~\"$ccdm_critical_pod\"} / pmrm_container_mem_limits_bytes{container!~\"$ccdm_critical_pod\"} * 100",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCSM CPU Memory PMRM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCSM_Critical_Pod_CPU_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_cpu_usage_nanocore{container=~\"$ccsm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccsm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM_Critical_Pod_CPU_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_cpu_usage_nanocore{container=~\"$ccsm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccsm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container=~\"$ccsm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container=~\"$ccsm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCSM_Critical_Pod_Mem_PMRM_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(pmrm_container_mem_usage_bytes{container=~\"$ccsm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccsm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM_Critical_Pod_Mem_PMRM_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(pmrm_container_mem_usage_bytes{container=~\"$ccsm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccsm_critical_pod\"}) by (container) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM_Critical_Pod_Mem_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container=~\"$ccsm_critical_pod\"} / pmrm_container_mem_limits_bytes{container=~\"$ccsm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCSM_Non_Critical_Pod_CPU_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_cpu_usage_nanocore{container!~\"$ccsm_critical_pod\"} / pmrm_container_cpu_limits_nanocore{container!~\"$ccsm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCSM_Non_Critical_Pod_Mem_PMRM",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pmrm_container_mem_usage_bytes{container!~\"$ccsm_critical_pod\"} / pmrm_container_mem_limits_bytes{container!~\"$ccsm_critical_pod\"} * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCRC CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CCRC Critical Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccrc1\",container=~\"$ccrc_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccrc1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccrc1\",container=~\"$ccrc_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccrc1\",resource=\"cpu\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCRC Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccrc1\",container=~\"$ccrc_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccrc1\",resource=\"cpu\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CCRC Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccrc1\",container=~\"$ccrc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccrc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccrc1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCRC Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccrc1\",container=~\"$ccrc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccrc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccrc1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCSM CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CCSM Critical Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccsm1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccsm1\",resource=\"cpu\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCSM Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccsm1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}} "
      }
     ]
    },
    {
     "title": "CCSM Critical Pods Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccsm1\",container=~\"$ccsm_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccsm1\",resource=\"memory\"})*100",
       "legendFormat": "{{container}} "
      }
     ]
    }
   ]
  },
  {
   "title": "CCPC CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CCPC Critical Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCPC Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"ccpc1\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCPC Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCPC Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"ccpc1\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"cpu\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCPC Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}} "
      }
     ]
    },
    {
     "title": "CCPC Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}} "
      }
     ]
    },
    {
     "title": "CCPC Critical Pods Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\",container=~\"$ccpc_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100",
       "legendFormat": "{{container}} "
      }
     ]
    },
    {
     "title": "CCPC Pods Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"ccpc1\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccpc1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccpc1\",resource=\"memory\"})*100",
       "legendFormat": "{{container}} "
      }
     ]
    }
   ]
  },
  {
   "title": "CCDM CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CCDM Critical Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccdm1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccdm1\",resource=\"cpu\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccdm1\",resource=\"memory\"})*100) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCDM Critical Pods Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"ccdm1\",container=~\"$ccdm_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"ccdm1\",resource=\"memory\"})*100",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCES CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CCES Critical Pods Average Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"cces1\",container=~\"$cces_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"cces1\",container=~\"$cces_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"cces1\",resource=\"memory\"})*100)by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCES Critical Pods Memory Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"cces1\",container=~\"$cces_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"cces1\",container=~\"$cces_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"cces1\",resource=\"memory\"})*100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCES Critical Pods Average CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{namespace=\"cces1\",container=~\"$cces_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"cces1\",resource=\"cpu\"}))by(container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CCES Critical Pods CPU Usage per Container [limits]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{namespace=\"cces1\",container=~\"$cces_critical_pod\"}[2m]))/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"cces1\",resource=\"cpu\"})",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SC CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SCP Critical Pod Average CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc1\"})/100000)) by (container)",
       "legendFormat": "SCP_{{container}}"
      }
     ]
    },
    {
     "title": "SCP Critical Pod CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc1\"})/100000)",
       "legendFormat": "SCP_{{container}}"
      }
     ]
    },
    {
     "title": "SCP-Critical-Pod-Avg-aMemory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc1\"})*100) by (container)",
       "legendFormat": "SCP_{{container}}"
      }
     ]
    },
    {
     "title": "SCP-Critical-Pod-Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc1\",container=~\"$scp_critical_pod\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc1\"})*100",
       "legendFormat": "SCP_{{container}}"
      }
     ]
    },
    {
     "title": "BSF-Critical-Pod--Avg-CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc1\"})/100000)) by (container)",
       "legendFormat": "SC_{{container}}"
      }
     ]
    },
    {
     "title": "BSF-Critical-Pod-CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"}[2m]))/on(pod,container)group_left()((container_spec_cpu_quota{name!=\"\",namespace=\"sc1\"})/100000)",
       "legendFormat": "SC_{{container}}"
      }
     ]
    },
    {
     "title": "BSF-Critical-Pod-Avg-Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc1\"})*100",
       "legendFormat": "SC_{{container}}"
      }
     ]
    },
    {
     "title": "BSF-Critical-Pod-Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"sc1\",container=~\"$bsf_critical_pod\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name!=\"\",namespace=\"sc1\"})*100",
       "legendFormat": "SC_{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCC CPU Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PCC_Critical_Pod_CPU_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100*irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"}[2m])/on(pod,contaier)group_left()(kube_pod_container_resource_limits{namespace=\"pcc1\",resource=\"cpu\",container=~\"$pcc_critical_pod\"})) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"}[2m])/on(pod,contaier)group_left()(kube_pod_container_resource_limits{namespace=\"pcc1\",resource=\"cpu\",container=~\"$pcc_critical_pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_Memory_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((container_memory_usage_bytes{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcc1\",resource=\"memory\"})*100) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCC_Critical_Pod_Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"pcc1\",container=~\"$pcc_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcc1\",resource=\"memory\"})*100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCG CPU/Memory/Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PCG_Critical_Pod_CPU_AVG",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"pcg1\",container=~\"$pcg_critical_pod\"}[2m])/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcg1\",resource=\"cpu\"}))) by (container)",
       "legendFormat": "({{container}})"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"pcg1\",container=~\"$pcg_critical_pod\"}[2m])/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcg1\",resource=\"cpu\"}))",
       "legendFormat": "{{pod}}_({{container}})"
      }
     ]
    },
    {
     "title": "PCG_Critical_Pod_Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"pcg1\",container=~\"$pcg_critical_pod\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcg1\",resource=\"memory\"})*100",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Non_Critical_Pod_CPU_Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(100*(irate(container_cpu_usage_seconds_total{name!=\"\",namespace=\"pcg1\",container!~\"$pcg_critical_pod|eric-pc-up-data-plane.*\"}[2m])/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcg1\",resource=\"cpu\"}))) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "PCG_Non_Critical_Pod_Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_usage_bytes{name!=\"\",namespace=\"pcg1\",container!~\"$pcg_critical_pod\"} - on(pod,container)container_memory_cache{name!=\"\",namespace=\"pcg1\"})/on(pod,container)group_left()(kube_pod_container_resource_limits{namespace=\"pcg1\",resource=\"memory\"})*100",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    }
   ]
  }
 ]
}