{
 "title": "Host_Disk",
 "description": "Host-Level-montor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host-Level-Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Host-Level-Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m]))",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m]))",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Host-Level-Disk bandwidth",
   "type": "graph",
   "description": "Read/write bandwidth",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "wps", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m]))",
     "legendFormat": "{{instance}}_{{device}}_Reads BW"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m]))",
     "legendFormat": "{{instance}}_{{device}}_Writes BW"
    }
   ]
  },
  {
   "title": "Host-Level-Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Host-Level-Disk bandwidth",
   "type": "graph",
   "description": "Read/write bandwidth",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "wps", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads BW"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes BW"
    }
   ]
  },
  {
   "title": "Host-Level-Disk Space Used Basic(EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  }
 ]
}