{
 "title": "Host_Network",
 "description": "Host-Level-montor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TCP_ReTran",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host-Level-Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*'}[30m])",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*'}[30m])",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Host-Level-Network Packet",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*'}[30m])",
     "legendFormat": "{{instance}}-{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Host-Level-Nerwork-Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~'$node'}[30m])",
     "legendFormat": "{{instance}}-{{device}}-receive"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~'$node'}[30m])",
     "legendFormat": "{{instance}}-{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Host-Level-Nerwork-Traffic Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}{{device}}-receive"
    },
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}{{device}}-transmit"
    }
   ]
  }
 ]
}