{
 "title": "Pod_MEM",
 "description": "pod-level-montor",
 "tags": [ "Pod-MEM" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "namespace",
    "label": "kube-namespace",
    "query": {
     "query": "label_values(container_last_seen{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container_MEM_limit",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{namespace=~\"$namespace\",container!=\"POD\",container!=\"\"}"
    }
   ]
  },
  {
   "title": "Container-Level-Memory Usage per Container[Exclude swap]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name=~\".+\",namespace=\"$namespace\",container!=\"\"}- on(pod,container,name)container_memory_cache{name=~\".+\",namespace=\"$namespace\",container!=\"\"})/on(pod,container)group_left()(container_spec_memory_limit_bytes{name=~\".+\",namespace=\"$namespace\",container!=\"\"}>0)*100",
     "legendFormat": "{{pod}}---{{container}}"
    }
   ]
  },
  {
   "title": "Container-level-MEM-Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\",namespace=\"$namespace\",container!=\"POD\",container!=\"init\",container!=\"\"}/on(pod,container)group_left()(container_spec_memory_limit_bytes{name=~\".+\",namespace=\"$namespace\",container!=\"POD\",container!=\"init\",container!=\"\"}>0)*100",
     "legendFormat": "{{pod}}---{{container}}"
    }
   ]
  }
 ]
}