{
 "title": "Pod_Network",
 "description": "pod-level-montor",
 "tags": [ "Pod-Network" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "namespace",
    "label": "kube-namespace",
    "query": {
     "query": "label_values(container_last_seen{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod-Level Network Traffic Packet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}-{{interface}}-receive"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}-{{interface}}-transmit"
    }
   ]
  },
  {
   "title": "Pod-Level Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}-{{interface}}-receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{name=~\".+\",namespace=\"$namespace\"}[30m])) by (pod,interface)",
     "legendFormat": "{{pod}}-{{interface}}-transmit"
    }
   ]
  },
  {
   "title": "Pod-Level-PacketDrop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    },
    {
     "expr": "-sum(irate(container_network_send_packets_dropped_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    }
   ]
  },
  {
   "title": "Pod-Level-ErrorPacket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_errors_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    },
    {
     "expr": "-sum(irate(container_network_send_errors_total{name=~\".+\",namespace=\"$namespace\"}[30m]))by(pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    }
   ]
  }
 ]
}