{
 "title": "PCG-UP-Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{namespace=\"pcg\"}, pod)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(pc_up_cpu_load_5s_percent,role)"
    }
   },
   {
    "name": "CPU",
    "query": {
     "query": "label_values(pc_up_cpu_load_5s_percent{role=~\"$role\"},cpu)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(pc_up_pktio_libpio_dpdk_extended_packets_total,port)"
    }
   },
   {
    "name": "upf_drop_reason",
    "query": {
     "query": "label_values(pc_up_upf_engine_dropped_packets_total,reason)"
    }
   },
   {
    "name": "rx_drop_reason",
    "query": {
     "query": "label_values(pc_up_payload_received_gtp_packets_total,reason)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DP Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"eric-pc-up-data-plane\",namespace=\"pcg\"}",
     "legendFormat": "Replicas"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",pod=~\"eric-pc-up-data-plane.*\"})",
     "legendFormat": "CPU size"
    }
   ]
  },
  {
   "title": "DP CPU Load per CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "pc_up_cpu_load_1s_percent{kubernetes_pod_name=~\"$pod\",role=~\"$role\",cpu=~\"$CPU\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{role}}_{{cpu}}"
    }
   ]
  },
  {
   "title": "Packet Loss on DP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "pc_up_pktio_libpio_dpdk_extended_packets_total{type=\"rx_dropped_packets\",kubernetes_pod_name=~\"$pod\",port=~\"$port\"} - (pc_up_pktio_libpio_dpdk_extended_packets_total{type=\"rx_dropped_packets\",kubernetes_pod_name=~\"$pod\",port=~\"$port\"} offset 1m)",
     "legendFormat": "{{kubernetes_pod_name}}_port-{{port}}_rx_dropped_packets"
    },
    {
     "expr": "pc_up_pktio_dropped_packets_total{kubernetes_pod_name=~\"$pod\",reason=\"egress_overload\"} - (pc_up_pktio_dropped_packets_total{kubernetes_pod_name=~\"$pod\",reason=\"egress_overload\"} offset 1m)",
     "legendFormat": "{{kubernetes_pod_name}}_egress_overload"
    }
   ]
  },
  {
   "title": "DP Deployment Layout",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info{pod=~\"eric-pc-up-data-plane.*\"})"
    }
   ]
  },
  {
   "title": "Stable sessions on DPs (k)",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "pc_up_upf_session_ctrl_cached_sessions{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(pc_up_upf_session_ctrl_cached_sessions)",
     "legendFormat": "Total sessions"
    }
   ]
  },
  {
   "title": "UPF Engine Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum(pc_up_upf_engine_dropped_packets_total{kubernetes_pod_name=~\"$pod\",reason=~\"$upf_drop_reason\"}) by (kubernetes_pod_name,reason) - sum(pc_up_upf_engine_dropped_packets_total{kubernetes_pod_name=~\"$pod\",reason=~\"$upf_drop_reason\"} offset 1m) by (kubernetes_pod_name,reason)",
     "legendFormat": "{{kubernetes_pod_name}}_{{reason}}"
    }
   ]
  },
  {
   "title": "GTP Rx Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(pc_up_payload_received_gtp_packets_total{action=\"drop\",protocol=\"ipv4\",reason=~\"$rx_drop_reason\"}) by (network_instance,interface,reason) - sum(pc_up_payload_received_gtp_packets_total{action=\"drop\",protocol=\"ipv4\",reason=~\"$rx_drop_reason\"} offset 1m) by (network_instance,interface,reason)",
     "legendFormat": "{{network_instance}}_{{interface}}_{{reason}}"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pc_up_pktio_received_bps)", "legendFormat": "pc_up_pktio_received_bps" },
    {
     "expr": "sum(pc_up_pktio_transmitted_bps)",
     "legendFormat": "pc_up_pktio_transmitted_bps"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pc_up_pktio_received_pps)", "legendFormat": "pc_up_pktio_received_pps" },
    {
     "expr": "sum(pc_up_pktio_transmitted_pps)",
     "legendFormat": "pc_up_pktio_transmitted_pps"
    }
   ]
  },
  {
   "title": "Packet Rate per DP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "pc_up_pktio_received_pps{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "-pc_up_pktio_transmitted_pps{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}