heat_template_version: 2017-09-01

description: >

parameters:

  networks_on_trunks:
    type: json

resources:

  port_resource_group_1:
    type: OS::Heat::ResourceGroup
    properties:
      count: 
        yaql:
          expression: $.data.len()
          data: { get_param: networks_on_trunks }
      resource_def:
        type: Resources/HotFiles/port-per-pool.yaml
        properties:
          pool_index: "%index%"
          networks_on_trunks: { get_param: networks_on_trunks }


outputs:
