######################################
## CNF general information
######################################
systemProfile: standard
nodeName: n186-eccd1-ccsm1
nodeType: CCSM
instance: 1

vnflcm:
  clusterName: n186-eccd1
  namespace: ccsm1
#  InstantiateVnfRequest:
#    applicationTimeOut: 3600
#    skipVerification: "true"

#nodeSelector:
#  node-pool: pool1
#  type: standard

users:
  day1:
  - username: ccsm-admin
    password: Changeme@1st
    groups:
    - ausf_admin
    - udm_sensitive_key_admin
    - udm_admin
    - system-admin
    - nrfagent-admin
    - hssepc_admin
    - ccsm-admin
    - eir_admin
  - username: ccsm-sec
    password: Changeme@1st
    groups:
    - udm_security_admin
    - nrfagent-security-admin
    - system-security-admin

license:
  customerId: "946060"
  swltId: STA-CCSM-37

cnom:
  fqdn: cnom.ccsm1-oam.n186-eccd1.seli.gic.ericsson.se

snmp:
  agentEngineId: 800000c10455444da1c1d1
  sourceIdentifier: 10.143.139.79

ddc:
  remotePath: ddc/n186-eccd1-ccsm1

vtap:
  tapagent: true
  remotePath: vtap/n186-eccd1-ccsm1

######################################
## CNF specific information
######################################
ccsm:
  ausf:
    instanceId: 76f4b62e-f3f7-454e-9562-415553a1c1d1
    host: ccsm1-ausf-5g-sig.site1-cluster1
    port: 443
  udm:
    instanceId: 841d1b7c-5103-11e9-8c09-55444da1c1d1
    host: ccsm1-udm-5g-sig.site1-cluster1
    port: 443
  eir:
    instanceId: 77fba27d-6a44-4074-8d9a-35475fa1c1d1
    host: ccsm1-eir-5g-sig.site1-cluster1
    port: 443
  hss:
    instanceId: 9448c0d3-6590-4e54-b90f-485353a1c1d1
    host: ccsm1-hss-epc-http-sig.site1-cluster1
    port: 80
    diameter:
      host: esm

######################################
## CNF certificates specific
######################################
certs:
  iccr-external-tls-certificate:
    p12: ../../../certs/n186-eccd1/ccsm1/ccsm1-iccr-server.p12
  eric-ccsm-sbi-server-certs:
    p12: ../../../certs/n186-eccd1/ccsm1/ccsm1-sbi-server.p12
  eric-ccsm-sbi-client-certs:
    p12: ../../../certs/n186-eccd1/ccsm1/ccsm1-sbi-client.p12

######################################
## CNF dimensioning specific
######################################
hpaReplica:
  eric-udm-cancelepclocation: {min: 2, max: 2}
  eric-udm-capacity: {min: 1, max: 20}
  eric-udm-eapauth: {min: 2, max: 2}
  eric-udm-eapprimeauth: {min: 2, max: 2}
  eric-udm-epsauth: {min: 5, max: 5}
  eric-udm-gbaauth: {min: 2, max: 2}
  eric-udm-imsauth: {min: 2, max: 2}
  eric-udm-iratamfdereg: {min: 2, max: 3}
  eric-udm-iratamflocation: {min: 2, max: 2}
  eric-udm-iratsndereg: {min: 2, max: 3}
  eric-udm-iwk5g2g: {min: 2, max: 2}
  eric-udm-sdmamdata: {min: 2, max: 2}
  eric-udm-sdmimplicitunsub: {min: 3, max: 4}
  eric-udm-sdmmultipledataset: {min: 3, max: 4}
  eric-udm-sdmnotif: {min: 2, max: 2}
  eric-udm-sdmnssai: {min: 2, max: 2}
  eric-udm-sdmsmdata: {min: 2, max: 3}
  eric-udm-sdmsmfselect: {min: 2, max: 2}
  eric-udm-sdmsubscriptions: {min: 5, max: 5}
  eric-udm-sdmuectxtsmf: {min: 2, max: 2}
  eric-udm-ueauth: {min: 3, max: 3}
  eric-udm-uecmamfget: {min: 2, max: 2}
  eric-udm-uecmamfderegnotifier: {min: 3, max: 3}
  eric-udm-uecmamfregupdate: {min: 2, max: 2}
  eric-udm-uecmreg: {min: 4, max: 5}
  eric-udm-uecmsmfderegistration: {min: 2, max: 2}
  eric-udm-uecmsmfregistration: {min: 3, max: 4}
  eric-ausf-capacity: {min: 2, max: 20}
  eric-ausf-engine: {min: 2, max: 2}
  eric-eir-eireic: {min: 5, max: 6}
  eric-eir-s13diameter: {min: 2, max: 2}
  eric-eir-diametereireic: {min: 2, max: 2}
  eric-hssepc-capacity: {min: 1, max: 20}
  eric-hssepc-s6adiameter: {min: 2, max: 2}
  eric-hssepc-iratsndereg: {min: 4, max: 5}
  eric-hssepc-s6aauthentication: {min: 5, max: 6}
  eric-hssepc-s6acancellocation: {min: 4, max: 5}
  eric-hssepc-s6adeletesubscriber: {min: 2, max: 2}
  eric-hssepc-s6ainsertsubscriber: {min: 2, max: 2}
  eric-hssepc-s6anotify: {min: 2, max: 2}
  eric-hssepc-s6apurge: {min: 2, max: 2}
  eric-hssepc-s6aupdatelocation: {min: 6, max: 7}
  eric-hssepc-soap: {min: 2, max: 2}
  eric-hssepc-subscriptionupdate: {min: 2, max: 2}

